### ISSUE TITLE
BigWigs Profile not applying correctly after update

### ISSUE THREAD

**Issue by devmozao** [Toxicom/toxiui#100]
### Description
BigWigs made a new release that resets the Profile and, since then, when you open the installer and reapply the BigWig profile, it doesn't apply it. It gets the style, but doesn't get the same anchors and size that was before.

Suggestion: maybe create a ToxiUI profile inside of BW, so we can just point to it and no need to rely on the installer. (or, maybe an import code copy button, since they're support it now)

### Lua error
no lua erros atm

### ToxiUI Status Report
![image](https://github.com/Toxicom/toxiui/assets/15485768/9fd97e46-5b60-48a9-8de3-957ff15ca065)

### Screenshots
![image](https://github.com/Toxicom/toxiui/assets/15485768/8dfaca0d-3ad6-4cd1-8720-953791d71353)

### To reproduce
1. Update addons
2. Once you log in, you'll receive the confirmation box on BW profile reset
3. Open the ToxiUI Installer, go to the BW button, apply, reload it.

**Comment by Toxicom** [comment]
This should be fixed in https://github.com/Toxicom/toxiui/releases/tag/v6.7.0-beta.2, do you mind testing and letting me know?

**Comment by devmozao** [comment]
@Toxicom didn't work on [v6.7.0-beta.3](https://github.com/Toxicom/toxiui/releases/tag/v6.7.0-beta.3)

I will try again tomorrow with a clean install on all addons and see what happens. Will come back with more info.
