### ISSUE TITLE
Attribute Icons?

### ISSUE THREAD

**Issue by Fendoran** [Toxicom/toxiui#101]
**Description:** 
Hi, I really love your addon, I don't know where I'd be without it, I've noticed you make customized icons, such as class icons and role icons, how cool wouldn't it be, if you could make Attribute Icons as well?

**Suggestion:**
Make Icons representing all attributes instead of just a boring text, hovering these icons (or line belonging to the attribute) would display the attribute name and the description you would otherwise get hovering the stat. 

(Stamina Icon) 4650
(Strength Icon) 3800

(Critical Icon) 18%
(Haste Icon) 15%
(Versatility Icon) 12%
(Mastery Icon) 14%

You get the gist (For all Attributes), would look extremely modern and nice looking!

**Comment by Toxicom** [comment]
I'll think about it, see if there are any free open source icons that would look nice, since I myself am no graphic artist 😆

**Comment by Fendoran** [comment]
Idk if there are, but I do know the GW2 UI addon does it, and it looks amazing, It's so good, you could check it and possibly take some inspiration from it? :)
![hero_panel](https://github.com/user-attachments/assets/06bf5b7d-3697-4d6e-b436-30aa1735aa10)

**Comment by Toxicom** [comment]
Started working on it, and it does seem odd with the gaps between icon and number.. I'd have to re-do the whole attributes frame and that's not something I wanna do, cause shit can very easily break :D
![image](https://github.com/user-attachments/assets/f4f42f8c-8d55-42d2-868a-50f5cb251dd9)

**Comment by Toxicom** [comment]
This might work though :)
![image](https://github.com/user-attachments/assets/68f0905c-ffcf-4dec-9065-ad3f16a693d7)

**Comment by Fendoran** [comment]
you could try and increase the sizes though? and have a option for a standalone icon, or Icon with Text? It looks amazing btw! :D

**Comment by Toxicom** [comment]
Decided for icon + label :)
Will be available next release f9238204fedcc59091bb900d6f53415a39fd97e7
