### ISSUE TITLE
Leatherworking profession not showing up

### ISSUE THREAD

**Issue by mlussier17** [Toxicom/toxiui#102]
### Description
I dont see my LW in the wunderbar

### Lua error
No LUA error

### ToxiUI Status Report
![image](https://github.com/Toxicom/toxiui/assets/16075140/43697a22-4696-4ac8-940b-40d0cbd0ae74)

### Screenshots
![image](https://github.com/Toxicom/toxiui/assets/16075140/4e344f88-0d60-4076-9c50-4a1b99312d5d)

![image](https://github.com/Toxicom/toxiui/assets/16075140/75c563fb-a27e-48d1-a5b6-41163bf2bfda)

### To reproduce
Nothing

**Comment by Toxicom** [comment]
Not enough space. Disable icons or reduce font.
