### ISSUE TITLE
Lua error after profile selection

### ISSUE THREAD

**Issue by HSniBBy** [Toxicom/toxiui#104]
### Description
What is the issue about?
Hey,

I have encountered the following problem.
I have installed ToxiUI for my main as normal,
I have also created a profile.

When I wanted to install ToxiUI on the rest of my twinks
the LUA error occurred. So I installed ToxiUI and then I selected the profile of my main on all my twinks and then the Lua error occurred.
I don't notice any other errors that affect playing WoW now, but I certainly shouldn't ignore the problem.

### Lua error
Message: ...terface/AddOns/ElvUI_ToxiUI/Core/Functions/Event.lua:175: script ran too long
Time: Sun Jul 14 01:10:34 2024
Count: 1
Stack: ...terface/AddOns/ElvUI_ToxiUI/Core/Functions/Event.lua:175: script ran too long
[string "=[tsm error check]"]:1: in main chunk
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_ToxiUI/Core/Functions/Event.lua"]:175: in function `TriggerEvent'
[string "@Interface/AddOns/ElvUI_ToxiUI/Core/Core.lua"]:32: in function `?'
[string "@Interface/AddOns/SharedMedia/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...dia/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/SharedMedia/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...dia/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/SharedMedia/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceDB-3.0/AceDB-3.0.lua"]:462: in function `SetProfile'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceDBOptions-3.0/AceDBOptions-3.0.lua"]:271: in function <...ries/Core/Ace3/AceDBOptions-3.0/AceDBOptions-3.0.lua:270>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:864: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:691>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceGUI-3.0/AceGUI-3.0.lua"]:66: in function <.../ElvUI_Libraries/Core/Ace3/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceGUI-3.0/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3-ElvUI/AceGUIWidget-DropDown-ElvUI.lua"]:107: in function <...ries/Core/Ace3-ElvUI/AceGUIWidget-DropDown-ElvUI.lua:98>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceGUI-3.0/AceGUI-3.0.lua"]:66: in function <.../ElvUI_Libraries/Core/Ace3/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceGUI-3.0/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceGUI-3.0/widgets/AceGUIWidget-DropDown-Items.lua"]:351: in function <...3/AceGUI-3.0/widgets/AceGUIWidget-DropDown-Items.lua:341>

Locals: 

### ToxiUI Status Report
Type `/tx status` in game and paste a screenshot of it here.
![WoWScrnShot_071424_011920](https://github.com/user-attachments/assets/f7eeab55-df56-4e35-8556-99c80fd9649c)

### Screenshots
Screenshots often say more than words

### To reproduce
If this issue is describing a bug, include some steps to reproduce the behavior

1.
2.
3.

**Comment by Toxicom** [comment]
How are you selecting the profile on your alts?

Here's a detailed guide on how to do that correctly: https://youtu.be/K7fLnUwbkCk?si=6H48bwWT-qX3jhSR

**Comment by HSniBBy** [comment]
ah okay, yes, I did it quite primitively. I selected an existing profile of mine and then used it for everyone. ^^ That's certainly not good, is it?

I'll do it again exactly like in your video and then nothing should go wrong, right?

**Comment by Toxicom** [comment]
If you select the correct private profile, should be fine

**Comment by HSniBBy** [comment]
thanks Sir for Help <3
