### ISSUE TITLE
Cooking Fire button on Cooking window

### ISSUE THREAD

**Issue by mrkhaglund** [Toxicom/toxiui#105]
### Description
Add Cooking Fire button to Cooking window for easy access

### Screenshots
![Namnlos](https://github.com/user-attachments/assets/7cba820d-2bf6-487d-84ac-56bb38ffa4ec)

**Comment by Toxicom** [comment]
Thanks for the suggestion!

For now, this does not seem like high priority. I'll fiddle around with it when I have time, but I don't see big appeal for this.

**Comment by Toxicom** [comment]
Will be available next release in the Professions module flyout.
ace2c3f5470679ef042c73b27cec12e03f1e2e7a
![image](https://github.com/user-attachments/assets/56e3f646-b245-4ab0-9c51-6b3451be748a)
