### ISSUE TITLE
Wunderbar MicroMenu doesn't open Specialization & Talents or Spellbook & Professions

### ISSUE THREAD

**Issue by mbryantms** [Toxicom/toxiui#112]
### Description
What is the issue about?

The MicroMenu module of the WunderBar does not open the proper menu when clicking on "Specialization & Talents" or "Spellbook & Professions". This is likely because of the spellbook update.

### Lua error
```lua
paste error here
```

### ToxiUI Status Report
Type `/tx status` in game and paste a screenshot of it here.

![image](https://github.com/user-attachments/assets/2394f16a-0bc1-438c-8a54-8a00a22d70d6)

### Screenshots
Screenshots often say more than words

### To reproduce
If this issue is describing a bug, include some steps to reproduce the behavior

1. Click on Wunderbar Micromenu for spellbook or talents.
2. Nothing happens.
3.

**Comment by Toxicom** [comment]
Will be fixed in `v6.7.5-beta.2`
