### ISSUE TITLE
Suggestion: Tome of Teleportation integration into Hearthstone module

### ISSUE THREAD

**Issue by penguinsane** [Toxicom/toxiui#113]
### Description
The addon Tome of Teleportation adds a nice menu to the UI that categorizes all of your available teleports into a nice menu, separated out by expansion or whatever else you set it to. My suggestion is to make it available as a selection (just called "Tome of Teleportation") to the binds menu of the Hearthstone module. So like for example, left click would be to use the Hearthstone as usual, but if I right click I could access the Tome of Teleportation UI. Or perhaps if the addon is loaded, then middle click could become an option to open the menu.

Tome of Teleportation works in Wunderbar as a module just fine, just would be nice to save a slot if ever possible :)

### Screenshots
![image](https://github.com/user-attachments/assets/9d1db9bd-c5e3-4505-80ef-2b4b7e2ab52a)

Thank you for your time!

**Comment by Toxicom** [comment]
https://discord.com/channels/769550106948141086/769550106948141088/1266060681397010484

**Comment by Toxicom** [comment]
https://github.com/davidmeen/TomeOfTeleportation/issues/51#issuecomment-2316200548
`TeleporterOpenFrame()`

**Comment by Toxicom** [comment]
This has been added in these commits:
- https://github.com/Toxicom/toxiui/commit/2992752f94681d43704c3b54d9c885f362bc0a62
- https://github.com/Toxicom/toxiui/commit/565788fc453e4a6045039cf2527b923e926c6969
