### ISSUE TITLE
release.json asset lost between v6.7.3-beta.1 and v6.7.3-beta.2

### ISSUE THREAD

**Issue by torkus** [Toxicom/toxiui#115]
### Description

The `release.json` release asset appears to have disappeared started at release v6.7.3-beta.2

**Comment by Toxicom** [comment]
`release.json` is generated automatically, I haven't changed anything in the packager. Why do you need it?

**Comment by torkus** [comment]
I maintain a catalogue of [wow addons available on Github](https://github.com/ogri-la/github-wow-addon-catalogue-go) for my [addon manager Strongbox](https://github.com/ogri-la/strongbox). The catalogue is regenerated weekly and I noticed that the presence of the `release.json` file disappeared, which is unusual.

The `release.json` file is preferred to scraping a Github release as it is less expensive to download and probably more accurate.

I think I tracked the problem down to your fork of the packager script, it's a little out of date:
![Screenshot at 2024-07-27 08-30-08](https://github.com/user-attachments/assets/7f619ccf-93e6-4251-9e7e-661f0cbec3c6)

Here is the release job with the warning and errors:
https://github.com/Toxicom/toxiui/actions/runs/10073080732/job/27846430418

And this is the interesting line:
https://github.com/Toxicom/toxiui/actions/runs/10073080732/job/27846430418#step:4:42

    /home/runner/work/_actions/Toxicom/packager/master/release.sh: line 1220: printf: 110000,11: invalid number

Which eventually leads to:
https://github.com/Toxicom/toxiui/actions/runs/10073080732/job/27846430418#step:4:1000

> There was an error creating release.json

**Comment by Toxicom** [comment]
I see, I'll try updating

**Comment by Toxicom** [comment]
I've updated our [packager](https://github.com/Toxicom/packager/commit/2cd0a85416168e53154eaa90f8ad186fe796be7c)

I believe the issue occured because I introduced [multiple versions TOC](https://github.com/Toxicom/toxiui/commit/716aec82b6614f763ac5d1440a9f04d4c6433bff#diff-705fbace2a0e3dbe17f5ca8eafcf405a0a742f3e57c74931512e67770e2199aeR9) and the old packager did not support it.

**Comment by torkus** [comment]
thanks for taking a look @Toxicom

**Comment by Toxicom** [comment]
`release.json` is back in [`v6.7.6-beta.1`](https://github.com/Toxicom/toxiui/releases/tag/v6.7.6-beta.1)
