### ISSUE TITLE
Cata ToxiUI Wunder Bar - hearthstone

### ISSUE THREAD

**Issue by bullka1** [Toxicom/toxiui#116]
CATACLYSM TOXIUI

Wunder Bar - Hearthstone:
Hello, can u pls add to the hearthstone mode in wunder bar : 

The Innkeeper's Daughter (id 64488) https://www.wowhead.com/cata/item=64488/the-innkeepers-daughter

and also

Jaina's Locket (id 52251) https://www.wowhead.com/cata/item=52251/jainas-locket

Thank you.
B.

**Comment by Toxicom** [comment]
https://github.com/Toxicom/toxiui/commit/1561c8867f13b14cbd9fafc0acbfb8a5cb1a5239
https://github.com/Toxicom/toxiui/commit/9aa38ad30b4afe287891f40c5d7dfc3895cba60f
