### ISSUE TITLE
Closing GameMenu triggers an error

### ISSUE THREAD

**Issue by Mera42** [Toxicom/toxiui#117]
### Description
Error triggering when closing Game menu (Esc key)

### Lua error
```lua
22x ElvUI_ToxiUI/Modules/Misc/GameMenuButton.lua:166: attempt to index field 'backgroundFade' (a nil value)
[string "@ElvUI_ToxiUI/Modules/Misc/GameMenuButton.lua"]:166: in function <ElvUI_ToxiUI/Modules/Misc/GameMenuButton.lua:165>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Hide'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:471: in function `SetUIPanel'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:502: in function `MoveUIPanel'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:555: in function `HideUIPanelImplementation'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:514: in function `HideUIPanel'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:177: in function <...ParentPanelManager/Mainline/UIParentPanelManager.lua:168>
[string "=[C]"]: in function `SetAttribute'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:898: in function `HideUIPanel'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:2806: in function <...rfaceBlizzard_UIParent/Mainline/UIParent.lua:2781>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `ToggleGameMenu'
[string "TOGGLEGAMEMENU"]:1: in function <[string "TOGGLEGAMEMENU"]:1>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'backgroundFade' (a nil value)"
self = <table> {
 iconCache = <table> {
 }
 modules = <table> {
 }
 baseName = "ElvUI_ToxiUI"
 defaultModuleState = true
 addonsToLoad = <table> {
 }
 hooks = <table> {
 }
 db = <table> {
 }
 enabledState = true
 isEnabled = false
 callOnInit = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 Initialized = true
 name = "ElvUI_ElvUI_ToxiUI_Misc"
 orderedModules = <table> {
 }
 moduleName = "Misc"
}

```

### ToxiUI Status Report
![image](https://github.com/user-attachments/assets/322b0c90-b6b4-43c9-8479-01446cf13d0e)

### Screenshots
![image](https://github.com/user-attachments/assets/1dbf56b3-3473-41a1-ad9e-6cc29377f57d)

### To reproduce
If this issue is describing a bug, include some steps to reproduce the behavior

1. Hitting Esc key (showing menu)
2. Close menu
3. Repeat

**Comment by Toxicom** [comment]
Works fine without issues for me:
![image](https://github.com/user-attachments/assets/e0a6b850-5f6a-4e76-ab06-426ff6c2e70f)

What do your settings look like here?
![image](https://github.com/user-attachments/assets/a0d49b82-91d9-4005-a2d2-f45f97d449dd)

**Comment by Mera42** [comment]
![image](https://github.com/user-attachments/assets/18d45c07-aa82-4e85-912e-e28159640021)

**Comment by Mera42** [comment]
Unticking Background Fade is triggering the error, no error is triggering when it is ticked

**Comment by Toxicom** [comment]
I see. The issue happens during closing of the game menu, it's trying to hide `backgroundFade` which does not exist.

I fixed it here, will be available next beta release.
https://github.com/Toxicom/toxiui/commit/56696948b6885f5324d19bac2e3ca5cca83f1356
