### ISSUE TITLE
Wunderbar Hearthstone module not working

### ISSUE THREAD

**Issue by Mera42** [Toxicom/toxiui#119]
### Description
Wunderbar Hearthstone module not working, when I do a Left Click, Right Click or Shift-Right Click, it does nothing (tried with no addons loaded).

### ToxiUI Status Report
![image](https://github.com/user-attachments/assets/1d588925-3b79-417b-9b44-c246003455c4)

### Screenshots
![image](https://github.com/user-attachments/assets/6d1980e1-f7ac-41cc-9618-aff5e0018469)

### To reproduce

1. Hovering Hearthstone module on Wunderbar
2. Try clicking
3. Module not responding

**Comment by Toxicom** [comment]
Can you make sure **Key Down** is enabled?
![image](https://github.com/user-attachments/assets/b6ec07c7-2041-4638-9e65-251de3b90d8e)

**Comment by Mera42** [comment]
**It does work when Key Down is checked**, any way to make it work without it to be checked ? I know KeyDown is a nice feature but I hate so much doing my actionbars and casting spells when dragging them (like consumables)

Everything else seems to work without to have it checked

**Comment by Toxicom** [comment]
Unfortunately no, whole WunderBar is programmed to be Key Down only. I suggest you get used to it, as Key Down is objectively the better option.

You can also set up so that dragging spells you need to hold shift, that way you won't cast spells while dragging.

**Comment by Mera42** [comment]
> You can also set up so that dragging spells you need to hold shift, that way you won't cast spells while dragging.

That's the issue here, I'm playing with a naga and a my bar 5 is also 6, 7, 8 when doing shift. ctrl or alt, that's why I'm not using a modifier to drag, if I do I can't put spells in those bars unless I disable the modifier
### Action paging
```
[nomod] 5; [mod:shift] 6; [mod:ctrl] 7; [mod:alt] 8;
```

![image](https://github.com/user-attachments/assets/1af26355-6df2-4840-95ef-f9dd733d2fdf)
(naga's buttons remapped ofc)

Thanks anyway, I'll deal with it !
