### ISSUE TITLE
[BUG] WunderBar: Databar visual bug

### ISSUE THREAD

**Issue by Toxicom** [Toxicom/toxiui#12]
### Description
1. Reputation bar/info text seems to show 100% regardless of what's the actual status.
   - Tooltip seems to be correct
2. Color is green?

### Screenshots

![image](https://user-images.githubusercontent.com/69549795/199124011-4a7ae9f3-775f-4577-af05-26472868ab46.png)

### To reproduce

1. `beta-8` build, happens every time

### Acceptance criteria

- [ ] ain't green no more
- [ ] shows correct bar/info text status

**Comment by bagelbits** [comment]
Is that using DataBar? That will crash and make the entire Wunderbar disappear if I try to use it. I have to reset Wunderbar in order to get it back.

**Comment by Toxicom** [comment]
![image](https://user-images.githubusercontent.com/69549795/199245338-91e3d910-ed4c-4f7c-a5a6-6c16aadaf6b5.png)
Think all bars are affected in wunderbar in being green

**Comment by Toxicom** [comment]
https://github.com/Toxicom/toxiui/commit/97484d9918dbe957b06e5e1f7e6668be1b41b646
