### ISSUE TITLE
Bars reset position when changing between dark mode and gradient. 

### ISSUE THREAD

**Issue by Dazlock** [Toxicom/toxiui#121]
### Description
When switching from Gradient mode or dark mode, it treats it as a new profile, rather than just switching the theme. 

### ToxiUI Status Report
n/a

### To reproduce
1. Create custom profile using dark mode, moving bars and resizing from default ToxiUI settings
2. Change back to gradient mode
3. Bars will have reset to default ToxiUI locations and settings

**Comment by Toxicom** [comment]
Should be fixed in next release e59c184
