### ISSUE TITLE
Power bar on warrior

### ISSUE THREAD

**Issue by RaVhen** [Toxicom/toxiui#122]
### Description
The power bar on warrior is not displayed as the same style of the target power bar, it instead takes the default elvui one

### Lua error
No error

### ToxiUI Status Report

![image](https://github.com/user-attachments/assets/e93b2b77-3314-4fd3-86f1-2307e66fbfa9)

### Screenshot
![image](https://github.com/user-attachments/assets/a795b041-cd33-4992-9697-1df4abee86fa)

### To reproduce
Enabled player power bar in elvui settings

**Comment by Toxicom** [comment]
Where it says "ToxiUI Status Report" we expect an image of `/tx status`, just as it says in the comment. Please include that :)

**Comment by Toxicom** [comment]
Player power bar got updated in `v6.7.8` - your last profile version is `v6.7.5` so naturally you do not have that change.

Please see my timestamp: https://youtu.be/giCLBwpUAow?si=MvK3s9lwhOQ8TCMi&t=435

**Comment by RaVhen** [comment]
Ok thanks! But I'll have my custom configuration lost while re doing the install right ?

**Comment by Toxicom** [comment]
Of course, just like in every other UI plugin.

**Comment by RaVhen** [comment]
Actually installed Elvui just to try your work <3 Okay then!
