### ISSUE TITLE
Wunderbar Error

### ISSUE THREAD

**Issue by FilthySerf** [Toxicom/toxiui#125]
### Description
Not sure, this error randomly pops up, it doesn't seem to be consistent either. This even has popped up with /tx debug on

### Lua error
11x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI_ToxiUI' tried to call the protected function 'Button:Show()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `Show'
[string "@ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua"]:394: in function `UpdateElement'
[string "@ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua"]:421: in function `UpdateElements'
[string "@ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua"]:186: in function <...I_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua:183>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
}

```

### ToxiUI Status Report
[Type `/tx status` in game and paste a screenshot of it here.](https://i.imgur.com/LYV6PfF.png)

### Screenshots
Screenshots often say more than words

### To reproduce
If this issue is describing a bug, include some steps to reproduce the behavior

1. I'm 90% sure it happens when pressing shift because I believe it coincides with the Statistics page of the Achievements Window popping up mid combat when I use action bar paging in ElvUI which has only done it when pressing shift. Like I said above though, it doesn't seem to be consistent on when it pops up, it just seems to be random. 
2.
3.

**Comment by Toxicom** [comment]
This is a taint and it's safe to ignore, as it doesn't actually break anything. Been happening for a long time.
