### ISSUE TITLE
key up - wunderbar

### ISSUE THREAD

**Issue by Sooleawa** [Toxicom/toxiui#126]
### Description
If i uncheck key down in elvui, wunderbar is not registering any mouse click.
![image](https://github.com/user-attachments/assets/baee6bd4-9d79-4667-869e-e63b03eb15a9)

### Lua error
```lua
no lua error
```

### ToxiUI Status Report
Type `/tx status` in game and paste a screenshot of it here.

![image](https://github.com/user-attachments/assets/741d9334-8b00-44af-84f5-d4f9fe29b96e)

### Screenshots
Screenshots often say more than words

### To reproduce
If this issue is describing a bug, include some steps to reproduce the behavior

1.   uncheck option
2.   click bar
3.

close this if unnecessary, i am not pro reporting stuff

**Comment by Toxicom** [comment]
This is expected behavior. WunderBar works only with KeyDown. We do not plan on changing this.
