### ISSUE TITLE
Bug: FadePersist misses early Blizzard_PlayerSpells loads

### ISSUE THREAD

**Issue by gekkenjuu** [Toxicom/toxiui#127]
In retail, the toxiui v6.7.9 FadePersist module [waits for Blizzard_PlayerSpells to load](https://github.com/Toxicom/toxiui/blob/v6.7.9/Modules/AddOns/FadePersist.lua#L131-L143) to apply its OnShow/OnHide hooks to `PlayerSpellsFrame`. Third-party addons may cause Blizzard_PlayerSpells to load earlier than `FP:Enable()` runs, which makes this scheme unreliable — if Blizzard_PlayerSpells is loaded early, FadePersist will never observe ADDON_LOADED for Blizzard_PlayerSpells, never apply the hooks, and hence fail to toggle fade overrides when the spellbook opens.

Consider using a helper method such as [EventUtil.ContinueOnAddOnLoaded](https://github.com/Gethe/wow-ui-source/blob/11.0.2/Interface/AddOns/Blizzard_SharedXML/EventUtil.lua#L52) (which would handle the already-loaded case for you), or checking whether `_G.PlayerSpellsFrame` already exists by the time `FP:Enable()` runs.

**Comment by Toxicom** [comment]
Thank you, I didn't consider that other AddOns might force load the AddOn before the spellbook is opened.

**Comment by Toxicom** [comment]
Should be good now with c0d4ba9
