### ISSUE TITLE
LUA error on Reload UI and Login

### ISSUE THREAD

**Issue by Nnavs** [Toxicom/toxiui#130]
### Description
What is the issue about? LUA error when I log in or reloadui. Otherwise, everything runs fine. 

### Lua error
`134x ...zzard_ActionBar/Mainline/MainMenuBarMicroButtons.lua:1704: attempt to compare number with nil
[string "@Blizzard_ActionBar/Mainline/MainMenuBarMicroButtons.lua"]:1704: in function `GetEdgeButton'
[string "@Blizzard_ActionBar/Mainline/MainMenuBarMicroButtons.lua"]:1734: in function `UpdateHelpTicketButtonAnchor'
[string "@Blizzard_ActionBar/Mainline/MainMenuBarMicroButtons.lua"]:1793: in function `Layout'
[string "@Blizzard_ActionBar/Mainline/MainMenuBarMicroButtons.lua"]:1842: in function `Layout'
[string "@Blizzard_ActionBar/Mainline/MainMenuBarMicroButtons.lua"]:407: in function <...zzard_ActionBar/Mainline/MainMenuBarMicroButtons.lua:406>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetParent'
[string "@ElvUI/Core/Modules/ActionBars/MicroBar.lua"]:229: in function `HandleMicroButton'
[string "@ElvUI/Core/Modules/ActionBars/MicroBar.lua"]:416: in function `SetupMicroBar'
[string "@ElvUI/Core/Modules/ActionBars/ActionBars.lua"]:1802: in function <ElvUI/Core/Modules/ActionBars/ActionBars.lua:1745>
...
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:422: in function `UIParentLoadAddOn'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:627: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:96: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:89: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:84: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:76: in function <...pansionLandingPage/Blizzard_WarWithinLandingPage.lua:72>
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:48: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:78: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:37: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:35>

Locals:
self = MicroMenu {
 layoutFramesGoingRight = true
 dirty = false
 stride = 12
 childYPadding = -5
 layoutFramesGoingUp = false
 numButtons = 12
 oldGridSettings = <table> {
 }
 isHorizontal = true
 childXPadding = -5
}
rightMost = true
topMost = false
firstButton = HelpMicroButton {
 FlashBorder = Texture {
 }
 tooltipText = "Customer Support"
 Background = Texture {
 }
 PushedBackground = Texture {
 }
 layoutIndex = 10
 textureName = "GameMenu"
 FlashContent = Texture {
 }
 QuickKeybindHighlightTexture = Texture {
 }
}
lastButton = MainMenuMicroButton {
 FlashBorder = Texture {
 }
 newbieText = "Modify your settings, change your hotkeys or exit the game."
 commandName = "TOGGLEGAMEMENU"
 tooltipText = "Game Menu"
 Background = Texture {
 }
 PushedBackground = Texture {
 }
 layoutIndex = 12
 updateInterval = 0
 textureName = "GameMenu"
 MainMenuBarPerformanceBar = Texture {
 }
 FlashContent = Texture {
 }
 QuickKeybindHighlightTexture = Texture {
 }
}
firstButtonX = nil
firstButtonY = nil
lastButtonX = 45.857143
lastButtonY = 1547.346924
(*temporary) = true
(*temporary) = 1547.346924
(*temporary) = 4
(*temporary) = "attempt to compare number with nil"
`

### Screenshots
Screenshots often say more than words
![Toxui](https://github.com/user-attachments/assets/28222220-474a-446f-aa3a-6fc42f329218)

Logging in and reloading UI

Thanks for any assistance! Loving the UI.

**Comment by Toxicom** [comment]
I don't see a single mention of ToxiUI in the error neither can I reproduce it. Please re-open the issue with more detailed instructions if you are certain this is something that ToxiUI causes.
