### ISSUE TITLE
Add the professional manufacturing page to the additional scaling module

### ISSUE THREAD

**Issue by longlixuans** [Toxicom/toxiui#131]
### Suggestions
1. It is recommended to add professional and professional manufacturing pages to the additional scaling module

(As a common page, the professional manufacturing page has not yet been added with custom scaling, and will appear relatively small at high resolution. I hope you can consider adding this function. Thank you very much)

**Comment by Toxicom** [comment]
What game version is this for? Professions scaling for Cataclysm & Vanilla already exists. On retail the professions window is huge already.

**Comment by longlixuans** [comment]
Thank you very much for your reply. It is the retail version. 
Now my overall UI scale is set to 0.56, and the character frame looks just right. But the text on the professional page is a little small. When setting the overall UI scale to 0.65, all fonts are clearer, but the character frame and pet frame will overlap by default.（2K resolution）

**Comment by Toxicom** [comment]
Please show screenshots because without them I have no idea what your UI looks like. 

Include /tx status in the screenshot, too. Don't crop the screenshot.

**Comment by longlixuans** [comment]
![1](https://github.com/user-attachments/assets/36d4b607-99b4-478c-8054-9151c93c4b1a)
![2](https://github.com/user-attachments/assets/eeb6ef73-84a3-482b-a705-7f0df6cd99ab)
![3](https://github.com/user-attachments/assets/c18839ad-e864-46b4-bfb7-cb273f89c09b)
![4](https://github.com/user-attachments/assets/fb9984b8-48f5-49b9-913a-563a456f7a99)
![5](https://github.com/user-attachments/assets/5cc5ef5a-c64a-4d8c-9b2d-4f99bcbcadb4)
![6](https://github.com/user-attachments/assets/78565af2-0c65-4d42-943b-53e641b0a3c2)

Here are some in-game screenshots

**Comment by Toxicom** [comment]
I've added professions scaling to the Additional Scaling module. We are not going to change the UI scale, as we're utilizing pixel perfect scale.
