### ISSUE TITLE
Bug in Repair Mount

### ISSUE THREAD

**Issue by valiztar** [Toxicom/toxiui#134]
### Description
What is the issue about?

It seems that in Spanish, it is not recognizing the correct repair mounts, it places a non-repair mammoth as an option.

the mammoth that places = https://www.wowhead.com/wotlk/es/item=44230/riendas-del-mamut-lanudo
the mammoth that should be = https://www.wowhead.com/wotlk/es/item=44234/riendas-del-mamut-de-tundra-de-viajero#teaches-ability

### Lua error
```lua
paste error here
```

### ToxiUI Status Report
Type `/tx status` in game and paste a screenshot of it here.
![image](https://github.com/user-attachments/assets/1fb3675b-609a-4738-80bf-05725c936a58)

### Screenshots
Screenshots often say more than words
![image](https://github.com/user-attachments/assets/08ec1923-5268-4e86-a322-03549447b1bf)

### To reproduce
If this issue is describing a bug, include some steps to reproduce the behavior

1. use Spanish language 
2. follow the instructions to switch the repair mount

**Comment by Toxicom** [comment]
Already fixed in https://github.com/Toxicom/toxiui/commit/1d4f0b540822f588810fa4179855616c550bfb2c, has nothing to do with Spanish language as we use Mount IDs
