### ISSUE TITLE
ActionButtonUseKeyDown cvar (required for GSE) breaks clcikable Wunderbae modules

### ISSUE THREAD

**Issue by wccropper** [Toxicom/toxiui#135]
### Description
I use GSE and with v11.0 it changed it so for GSE macros to work they require the cvar to be ActionButtonUseKeyDown be false. This breaks several of Wunderbar's modules. MicroMenu, Currency, Hearthstone

### Lua error
no error. clicking many of the Wunderbar modules do nothing.

### ToxiUI Status Report
![image](https://github.com/user-attachments/assets/6ef38533-0d6a-495d-98d1-1542943fd553)

### To reproduce
Change the cvar and try clicking on one of the above modules.

**Comment by Toxicom** [comment]
We're not changing this behavior. Key down is objectively better.

**Comment by Toxicom** [comment]
Actually was able to come up with a compromise where both parties are happy. Changed WunderBar's click registering to check for the CVar and based on that register either `AnyDown` or `AnyUp`

From my brief testing seems to work, let me know how it goes.
https://github.com/Toxicom/toxiui/commit/06191e5ebc187c4b0c9d34007bf70eeeda338d90

**Comment by wccropper** [comment]
Ho do I easily get these changes into my install?

**Comment by Toxicom** [comment]
Either clone the git repository, or wait for the `v6.8.4-beta.1` release that I'm currently deploying.

**Comment by Toxicom** [comment]
https://github.com/Toxicom/toxiui/releases/tag/v6.8.4-beta.1

**Comment by wccropper** [comment]
I will wait and reply back! You are an amazing dev. By far my favorite ElvUI edit ever. Donation incoming!

**Comment by wccropper** [comment]
Yeah, all working. Thanks again!

**Comment by Toxicom** [comment]
Nice :)
