### ISSUE TITLE
Quest Objectives Keep DIsapeering in Dungeons

### ISSUE THREAD

**Issue by UghMyUserNameWasTaken** [Toxicom/toxiui#136]
### Description
Quest Objectives keep disappearing in dungeons. Including M+ stuff like mob kill%.

### Lua error
```lua
paste error here
```

### ToxiUI Status Report
![image](https://github.com/user-attachments/assets/3b63bd5c-4bde-476e-9502-d5485f3a003d)

### Screenshots
Screenshots often say more than words

### To reproduce
If this issue is describing a bug, include some steps to reproduce the behavior

1. Be in a dungeon
2. After a while it just vanishes
3. To get it back must /reload

**Comment by Toxicom** [comment]
Has nothing to do with ToxiUI. Known issue of ElvUI.

> Quest objective frame hiding
With the blizzard changes, the objective frame is a bit buggy atm
You can disable it in ElvUI - General - Blizz Improvements - Objective Frame  - 
Uncheck Auto hide

**Comment by UghMyUserNameWasTaken** [comment]
Thank You!
