### ISSUE TITLE
Wunderbar mouseover issues

### ISSUE THREAD

**Issue by billriess** [Toxicom/toxiui#143]
### Description
When Wunderbar is set to mouseover, flyout menus (ie: crafting professions) will auto-hide but their hitboxes remain active even though they are transparent. It would be nice if hovering over the flyout menu would prevent the Wunderbar from auto-hiding. At the very least, when the Wunderbar is hidden, it should fully close the flyout menus.

### ToxiUI Status Report
![image](https://github.com/user-attachments/assets/fe933f4f-ed90-4a6f-a083-515f7d4ee66b)

### Screenshots
![ezgif-2-a8cdebc59c](https://github.com/user-attachments/assets/3b6ad486-5464-4ba8-bed7-5cfe6385e444)

### To reproduce
If this issue is describing a bug, include some steps to reproduce the behavior

1. `/tx wunderbar`
2. `General` -> ✅ Mouseover Only
3. Right click a profession to open the flyout menu
4. Hover over the flyout menu items and they will fade out but remain active

**Comment by Toxicom** [comment]
Should be fixed in https://github.com/Toxicom/toxiui/commit/2121983fa23f0cd4180088ce71994f1718190632.

Please test with `v6.8.8-beta.1` and close the issue if it's fixed ✌️

**Comment by billriess** [comment]
This is fixed, thank you.
