### ISSUE TITLE
Empty AFK Screen

### ISSUE THREAD

**Issue by billriess** [Toxicom/toxiui#145]
### Description
The AFK screen is not showing much data. This has always looked like this for me. Everything is installed on a clean profile and all AFK-related settings are default.

### ToxiUI Status Report
![image](https://github.com/user-attachments/assets/b88c45d1-6c70-4716-9429-4b1cf1eeeaec)

### Screenshots
![image](https://github.com/user-attachments/assets/7741b3d2-6eee-47df-a5e8-c96acc03e98f)
![image](https://github.com/user-attachments/assets/040b81ff-54ba-4f5b-8838-eea21440c9ae)

### To reproduce
If this issue is describing a bug, include some steps to reproduce the behavior

1. Type `/afk`

**Comment by Toxicom** [comment]
Can you reproduce this with `/tx debug on`? Also, can you `/fstack` around and see if any AFK elements get created at all?

**Comment by billriess** [comment]
![image](https://github.com/user-attachments/assets/cddc4b3a-0271-4fe3-b999-e807dacdd28c)

Still happens with `/tx debug on`.

**Comment by Toxicom** [comment]
What's interesting is that you do get *some* elements of the AFK mode working, like the background frame and the text at the bottom.. I'll investigate further, but last I checked, it works flawlessly for me 🤔

**Comment by Toxicom** [comment]
`0.6` UI Scale could also be related to this. If it's not too much of a bother, can you create a new environment where you're using default ToxiUI installation settings (UI scale being one of them)

**Comment by billriess** [comment]
Yeah its strange, the camera does rotate and the model will animate but that's basically it.

**Comment by billriess** [comment]
![image](https://github.com/user-attachments/assets/081ae0c1-892d-408d-8a17-d78bf133e51f)

Fresh profile, still happens

**Comment by billriess** [comment]
Lowering the resolution to 1440p I see this:
![image](https://github.com/user-attachments/assets/f2434ca0-f4fe-4e93-8d57-54f8d6751ff0)

So it seems to be resolution related.

**Comment by billriess** [comment]
![image](https://github.com/user-attachments/assets/c3117a42-c8f1-489b-8474-9a8b98d7bd30)

```LUA
    -- Debug frame position and size
    print("Bottom Frame Coordinates:")
    print("Top: ", self.frame.bottom:GetTop())
    print("Right: ", self.frame.bottom:GetRight())
    print("Bottom: ", self.frame.bottom:GetBottom())
    print("Left: ", self.frame.bottom:GetLeft())
    
    -- Debug frame size
    print("Width: ", self.frame.bottom:GetWidth())
    print("Height: ", self.frame.bottom:GetHeight())

    -- Ensure frame visibility by adjusting anchors and offsets
    self.frame.bottom:ClearAllPoints()
    self.frame.bottom:SetPoint("TOPLEFT", UIParent, "TOPLEFT", 0, 0)
```
    
Adding the above code results in most of the UI now being shown but the 3D model is now gone. It seems something is off with the anchor.

The debug print:

> [06:43] Bottom Frame Coordinates: 
> [06:43] Top:  2159.4074707031 
> [06:43] Right:  2276.4443359375 
> [06:43] Bottom:  -0.5925926566124 
> [06:43] Left:  -0.88889557123184 
> [06:43] Width:  2277.3332519531 
> [06:43] Height:  2160.0002441406

**Comment by Toxicom** [comment]
I see the 3D model even with the code you've provided.
![image](https://github.com/user-attachments/assets/6c67c0ce-b5f3-4117-858b-717305d2f98d)

Width is `2px` more than it should be, otherwise seems fine.
![image](https://github.com/user-attachments/assets/ca5696c8-87b8-4ea9-81e5-ca3d42f021fc)

**Comment by Toxicom** [comment]
Potentially fixed with `v6.8.8-beta.4`. Can you test that and let me know?

**Comment by Toxicom** [comment]
Re-open the issue if the error persists.

**Comment by billriess** [comment]
This looks good now, nice job!
