### ISSUE TITLE
Siege of Boralus M+ Season 1 Portal ID still appears to be incorrect

### ISSUE THREAD

**Issue by mdpaquin** [Toxicom/toxiui#148]
### Description
The WunderBar HearthStone module still appears to have the incorrect ID for Siege of Boralus defined. As a result, the icon is not shown in the M+ Port dropdown even though the portal has been unlocked.

The codebase was recently updated with the correct IDs for Season 1 and, as part of that commit, Siege of Boralus was updated to ID 464256. My port ID in my spellbook is 445418. I suspect there might be different port IDs depending on if you unlocked the port back in BFA or as part of TWW Season 1. Is it possible to define multiple IDs for the same port? If so it should be as simple as adding the line...I can create a PR if you need me to.

### Lua error
```lua
paste error here
```

### ToxiUI Status Report
![image](https://github.com/user-attachments/assets/fd9e3118-5124-4f16-ba93-971e3e0f2692)

### Screenshots
![image](https://github.com/user-attachments/assets/66bc922f-99cc-496e-a0ab-375d76cbf2ed)

### To reproduce
If this issue is describing a bug, include some steps to reproduce the behavior

1. Have the Siege of Boralus Portal unlocked
2. Open the M+ Portal menu of the Hearthstone Wunderbar module

**Comment by Toxicom** [comment]
It's a possibility that horde & alliance have separate portal IDs, same as mage's for Shattrath etc.

I'll add this ID too, thank you.

**Comment by Toxicom** [comment]
> Is it possible to define multiple IDs for the same port?

Yes, as when generating the list to render, we iterate through all the IDs and check if the character has that spell id known.

**Comment by mdpaquin** [comment]
The horde and alliance theory is very plausible actually since there are 2 entrances to the dungeon and the alliance one ports you in the middle of Boralus...I doubt the Horde one does the same 🤣

**Comment by Toxicom** [comment]
5892fdb5d2a7340854abd3580ba2ac0b772abfd1

**Comment by Toxicom** [comment]
Should be fixed in `v6.8.8-beta.2`.

Re-open the issue if that's not the case.
