### ISSUE TITLE
Error when loading BigWigs profile via installer

### ISSUE THREAD

**Issue by dsypher2** [Toxicom/toxiui#149]
### Description
Error when loading BigWigs profile via installer

### Lua error
5x ...aceElvUI_ToxiUI/Modules/Profiles/BigWigs.lua:15: attempt to call field 'RegisterProfile' (a nil value)
[string "@ElvUI_ToxiUI/Modules/Profiles/BigWigs.lua"]:15: in function `BigWigs'
[string "@ElvUI_ToxiUI/Modules/Installer/Dialog.lua"]:384: in function <...aceElvUI_ToxiUI/Modules/Installer/Dialog.lua:383>

Locals:
self = <table> {
 modules = <table> {
 }
 baseName = "ElvUI_ToxiUI"
 defaultModuleState = true
 hooks = <table> {
 }
 enabledState = true
 isEnabled = false
 defaultModuleLibraries = <table> {
 }
 Initialized = true
 name = "ElvUI_ElvUI_ToxiUI_Profiles"
 orderedModules = <table> {
 }
 moduleName = "Profiles"
}
profileName = "ToxiUI"
profileString = "BW1:LvvZUTXnqySyJbAGtqLSRvAq7b5I0MMdXqsU2bXxkYAjhlxjBbP1nj(sxQvu7sKvlzj56FkkAb0PEwpc(rqh6dGU1Bl0H(a4hbJ(auoC)rYX6a1YHZpFZ3mCOXFZkmcleipChQGij0qX3ndpI5NT9OA2N0j2043F8nHu(iuq(b93VXX2n6gVsRnE0JMN6L9PbuU48(SiolaVxhZkB9kd9Qv)GOeb1GLFWSRhhJdtKyQxTCVcLjWS)v4Ga6f7zQpRAFkhf6H3tVBhTOAC8GK9Apw72um0dlLKqpXFvGtJKbKqm)KtTB184gJhsdL9i)g(fZHC8ugdZDrcS)4HObyjzeUJz1TQDdCyBAi11NthH91eYbktpgncZFz52LFvLkAFbcIlz56JK(thqeSa0vGBwzkyYjjrFM9Hn3)NsHWupo9ItzxG4deoJJeyIRIZDU2najeUa75KhoaPv7IciEHD728ThAF9OfGIvmufCvaLls4TMlXxkbt11HJmv)yBar4TkQSdN62tI4Y3esg5WkPLRqtDch7cLu9HwTACG9uWpNmCOalFVXTGIVrWuk1fP0ZHToizFknya9IWJJg1hZfkhcgDFhgBofupXBFWqVPhd5Qq8k3aBACjtzaGqhwXL9CVlimSJo8wu(ampjRmmmmVgeEiM45lFQwbiPt574clb)pS6nWMLRMzCeu8g)YY20ljN2uJK6ybsgXvu6cTGIW3Q5182fN5Agjss75IcWPOgsGd44Fnch6E1H)4)oe(Pkt3JvIFoBT7M32xXWDzKlXb3SizHaBMOPU6bh3sLEIhF9cLCyF5YLxOYwhsavysTfYH2l32CVYUcpRF3OGd9K(pKvy5IrJbEPj(D7VMLjcWBX5zokrHopOYwVENfRBxZK90mvacCFKq2r1KqCdWIIP9Kz4W2N4(rvclmtkO3P8M2czmbm5DKbs)nhdFEgLoYihu6lO7Uud473ysswLF)4onZndpx1lROPn(uuQl1Mt6Js(*temporary) = nil
(*temporary) = "|cffffffffToxi|r|cff18a8ffUI|r"
(*temporary) = "BW1:LvvZUTXnqySyJbAGtqLSRvAq7b5I0MMdXqsU2bXxkYAjhlxjBbP1nj(sxQvu7sKvlzj56FkkAb0PEwpc(rqh6dGU1Bl0H(a4hbJ(auoC)rYX6a1YHZpFZ3mCOXFZkmcleipChQGij0qX3ndpI5NT9OA2N0j2043F8nHu(iuq(b93VXX2n6gVsRnE0JMN6L9PbuU48(SiolaVxhZkB9kd9Qv)GOeb1GLFWSRhhJdtKyQxTCVcLjWS)v4Ga6f7zQpRAFkhf6H3tVBhTOAC8GK9Apw72um0dlLKqpXFvGtJKbKqm)KtTB184gJhsdL9i)g(fZHC8ugdZDrcS)4HObyjzeUJz1TQDdCyBAi11NthH91eYbktpgncZFz52LFvLkAFbcIlz56JK(thqeSa0vGBwzkyYjjrFM9Hn3)NsHWupo9ItzxG4deoJJeyIRIZDU2najeUa75KhoaPv7IciEHD728ThAF9OfGIvmufCvaLls4TMlXxkbt11HJmv)yBar4TkQSdN62tI4Y3esg5WkPLRqtDch7cLu9HwTACG9uWpNmCOalFVXTGIVrWuk1fP0ZHToizFknya9IWJJg1hZfkhcgDFhgBofupXBFWqVPhd5Qq8k3aBACjtzaGqhwXL9CVlimSJo8wu(ampjRmmmmVgeEiM45lFQwbiPt574clb)pS6nWMLRMzCeu8g)YY20ljN2uJK6ybsgXvu6cTGIW3Q5182fN5Agjss75IcWPOgsGd44Fnch6E1H)4)oe(Pkt3JvIFoBT7M32xXWDzKlXb3SizHaBMOPU6bh3sLEIhF9cLCyF5YLxOYwhsavysTfYH2l32CVYUcpRF3OGd9K(pKvy5IrJbEPj(D7VMLjcWBX5zokrHopOYwVENfRBxZK90mvacCFKq2r1KqCdWIIP9Kz4W2N4(rvclmtkO3P8M2czmbm5DKbs)nhdFEgLoYihu6lO7Uud473ysswLF)4onZndpx1lROPn(uuQl1Mt6Js6(*temporary) = "ToxiUI"
(*temporary) = "attempt to call field 'RegisterProfile' (a nil value)"
F = <table> {
 Log = <table> {
 }
 Color = <table> {
 }
 Event = <table> {
 }
 ProtectedCall = <table> {
 }
 Table = <table> {
 }
 String = <table> {
 }
}
TXUI = <table> {
 IsRetail = true
 DevTag = "|cffef5350[BETA]|r"
 RetailSeason = "tww1"
 modules = <table> {
 }
 DevRelease = true
 MetaFlavor = "Mainline"
 defaultModuleState = true
 RegisteredModules = <table> {
 }
 LogLevel = 4
 hooks = <table> {
 }
 enabledState = true
 Version = "6.8.8"
 isEnabled = false
 Changelog = <table> {
 }
 PreventProfileUpdates = true
 initializedSafe = true
 defaultModuleLibraries = <table> {
 }
 GitHash = "v6.8.8-beta.2"
 initialized = true
 Flavor = 3
 IsCata = false
 baseName = "ElvUI_ToxiUI"
 orderedModules = <table> {
 }
 AnimationGetFunc = <table> {
 }
 AnimationSetFunc = <table> {
 }
 Modules = <table> {
 }
 IsVanilla = false
 ReleaseVersion = "6.8.8"
 ClientBuildVersion = 110005
 Title = "|cffffffffToxi|r|cff18a8ffUI|r"
 name = "ElvUI_ElvUI_ToxiUI"
 AddOnName = "ElvUI_ToxiUI"
 moduleName = "ElvUI_ToxiUI"
 DelayedWorldEntered = true
}

```

### ToxiUI Status Report
![image](https://github.com/user-attachments/assets/bb1f1467-0983-4d0c-b74f-848623f8bf1c)

### Screenshots
Screenshots often say more than words

### To reproduce
If this issue is describing a bug, include some steps to reproduce the behavior

1.
2.
3.

**Comment by Toxicom** [comment]
Are you on the latest BigWigs version? They recently updated their API to expect `RegisterProfile` function instead of the old one.
https://github.com/BigWigsMods/BigWigs/blob/master/API.lua#L125-L147

**Comment by Toxicom** [comment]
https://github.com/BigWigsMods/BigWigs/commit/9d9cd50340fb94896739b5aec14c866dcdef76ba

**Comment by dsypher2** [comment]
fresh install of BW

**Comment by Toxicom** [comment]
It's possible that they still haven't made a public release. In that case, reverting to `v6.8.8-beta.1` will fix the issue you're facing.

**Comment by Toxicom** [comment]
Fixed with latest BigWigs releases.
