### ISSUE TITLE
Stuck Pixel with ToxiUI

### ISSUE THREAD

**Issue by ThaBlakSheep** [Toxicom/toxiui#155]
### Description
There is a pixel that I cannot find the module that controls it, and it is only present when using ToxiUI.

### ToxiUI Status Report
![ToxiUI Status](https://github.com/user-attachments/assets/aecdb5ad-081b-4934-9557-792e5988b393)

### Screenshots
![ToxiUI dot](https://github.com/user-attachments/assets/1681ee9c-fece-4571-b369-b3477cc24bf9)
![Stock UI](https://github.com/user-attachments/assets/a0244723-f09f-4ae1-84fc-85a471cd81c2)

### To reproduce
If this issue is describing a bug, include some steps to reproduce the behavior

1. Its visible all the time, regardless of character.
2. I can mouse over it and it is behind the cursor so it is not a dead pixel. 
3. It is there if the chat box is open or not.

**Comment by Toxicom** [comment]
Nothing to do with ToxiUI. Known issue of ElvUI.
