### ISSUE TITLE
Mouseover on currency of WunderBar

### ISSUE THREAD

**Issue by dolikemath** [Toxicom/toxiui#156]
### Description
What is the issue about?

Mouseover doesn't work on currency of WunderBar for other realm. It works for only Azshara(KR) realm.

### Lua error
```lua
Message: Interface/AddOns/ElvUI/Core/General/Math.lua:416: bad argument #1 to 'abs' (number expected, got table)
Time: Wed Dec 18 22:39:53 2024
Count: 2
Stack: Interface/AddOns/ElvUI/Core/General/Math.lua:416: bad argument #1 to 'abs' (number expected, got table)
[string "@Interface/AddOns/ElvUI/Core/General/Math.lua"]:416: in function `FormatMoney'
[string "@Interface/AddOns/ElvUI_ToxiUI/Modules/WunderBar/SubModules/Currency.lua"]:197: in function `UpdateTooltip'
[string "@Interface/AddOns/ElvUI_ToxiUI/Modules/WunderBar/SubModules/Currency.lua"]:156: in function `OnEnter'
[string "@Interface/AddOns/ElvUI_ToxiUI/Modules/WunderBar/Modules.lua"]:137: in function `ModuleOnEnter'
[string "@Interface/AddOns/ElvUI_ToxiUI/Modules/WunderBar/SubModules/Currency.lua"]:448: in function <...vUI_ToxiUI/Modules/WunderBar/SubModules/Currency.lua:447>
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua"]:92: in function <...lvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:87>

Locals: self = <table> {
 mylevel = 80
 Bags = <table> {
 }
 privateVars = <table> {
 }
 modules = <table> {
 }
 myspecRole = "DAMAGER"
 PriestColors = <table> {
 }
 db = <table> {
 }
 Layout = <table> {
 }
 Distributor = <table> {
 }
 MountText = <table> {
 }
 INCOMPATIBLE_ADDONS = <table> {
 }
 TimeIndicatorColors = <table> {
 }
 TimeThreshold = 3
 WorldMap = <table> {
 }
 TimeColors = <table> {
 }
 Tooltip = <table> {
 }
 ShortValueDec = "%.1f"
 oUF = <table> {
 }
 Classic = false
 myrole = "DAMAGER"
 UFParent = ElvUFParent {
 }
 InfoColor2 = ""
 myname = "나쁜성기사칠일"
 ActionBars = <table> {
 }
 DebugTools = <table> {
 }
 twoPixelsPlease = false
 ConfigModeLayouts = <table> {
 }
 DataTexts = <table> {
 }
 ClassName = <table> {
 }
 CreatureTypes = <table> {
 }
 Auras = <table> {
 }
 ClassicAnnivHC = false
 ReverseTimer = <table> {
 }
 TagFunctions = <table> {
 }
 myClassID = 2
 UnlocalizedClasses = <table> {
 }
 MinimapSize = 276
 callbacks = <table> {
 }
 hooks = <table> {
 }
 SpecName = <table> {
 }
 GemTypeInfo = <table> {
 }
 StyleFilterDefaults = <table> {
 }
 physicalWidth = 2560
 versionString = "13.81"
 DataBars = <table> {
 }
 InfoColor = ""
 AFK = <table> {
 }
 CreatedMovers = <table> {
 }
 myLocalizedFaction = "호드"
 myrace = "BloodElf"
 StaticPopup_DisplayedFrames = <table> {
 }
 VehicleLocks = <table> {
 }
 myLocalizedRace = "블러드 엘프"
 myclass = "PALADIN"
 wowdate = "Nov 19 2024"
 PopupDialogs = <table> {
 }
 Chat = <table> {
 }
 myrealm = "세나리우스"
 LayoutMoverPositions = <table> {
 }
 global = <table> {
 }
 orderedModules = <table> {
 }
 Misc = <table> {
 }
 LibsMinor = <table> {
 }
 UnitFrames = <table> {
 }
 uiscale = 0.533333
 resolution = "2560x1440"
 TBC = false
 AnimElastic = <table> {
 }
 QualityColors = <table> {
 }
 media = <table> {
 }
 data = <table> {
 }
 Options = <table> {
 }
 ClassicHC = false
 HiddenFrame = Frame {
 }
 Media = <table> {
 }
 name = "ElvUI"
 TimeFormats = <table> {
 }
 ShortPrefixStyles = <table> {
 }
 versionDev = false
 Blizzard = <table> {
 }
 wowbuild = 57689
 RegisteredInitialModules = <table> {
 }
 TotemTracker = <table> {
 }
 RegisteredCooldowns = <table> {
 }
 SpecInfoBySpecID = <table> {
 }
 ObjectEventTable = <table> {
 }
 title = "ElvUI"
 EditorMode = <table> {
 }
 MapInfo = <table> {
 }
 frames = <table> {
 }
 physicalHeight = 1440
 NewSignNoWhatsNew = ""
 ClassicSOD = false
 Retail = true
 MountIDs = <table> {
 }
 AnimShake = <table> {
 }
 DisabledMovers = <table> {
 }
 mult = 1
 UserList = <table> {
 }
 MediaUpdated = true
 myspecName = "징벌"
 PixelMode = true
 serverID = 2116
 PrivateAuras = <table> {
 }
 myspecIcon = 135873
 initialized = true
 charSettings = <table> {
 }
 GetFormattedTextStyles = <table> {
 }
 myguid = "Player-2116-087906E9"
 FrameLocks = <table> {
 }
 loadedtime = 506918.868000
 Spacing = 0
 ConfigTooltip = ElvUI_ConfigTooltip {
 }
 SpecInfoBySpecClass = <table> {
 }
 Border = 1
 EasyMenu = ElvUI_EasyMenu {
 }
 statusBars = <table> {
 }
 SpellBookTooltip = ElvUI_S
```

### ToxiUI Status Report
Type `/tx status` in game and paste a screenshot of it here.

### Screenshots
Screenshots often say more than words

![캡처](https://github.com/user-attachments/assets/d169b43f-a310-412f-970d-3fa7474694fc)
Other realm.

![캡처2](https://github.com/user-attachments/assets/4fff63f8-279d-4340-9116-a3e5bca5cb90)
Azshara realm.

### To reproduce
If this issue is describing a bug, include some steps to reproduce the behavior

1.
2.
3.

**Comment by Toxicom** [comment]
Can you please provide the rest of the information as requested in the issue template?

**Comment by dolikemath** [comment]
I updated the screenshot.

**Comment by Toxicom** [comment]
Can you install BugGrabber & BugSack addons, see if you're getting any Lua errors?

Also, how many characters do you have on the realm that's not working?

Can you reproduce this issue with `/tx debug on`?

**Comment by dolikemath** [comment]
All characters(7) on Cenarius(KR) realm don't work.

And, I updated the lua errors.

**Comment by Toxicom** [comment]
Thanks for providing additional information!

Can you try disabling all addons except elvui (by running `/edebug on`) and then creating a Currency DataText in ElvUI and seeing if that works?

I inspected the error you sent and it fails on this line:
`amountText = E:FormatMoney(_G.ElvDB.gold[realm][k], style, true),`
Which makes me believe there's something wrong in ElvUI's database for your characters.

**Comment by Toxicom** [comment]
Additionally, can you open the `ElvUI.lua` file in `WoW/_retail_/WTF/Account/ID/SavedVariables/ElvUI.lua` and find a table with the `gold` key? It should look something like this:
```lua
	["gold"] = {
		["Tarren Mill"] = {
			["Toxihunt"] = 3897277151,
			["Toxivoid"] = 34748200,
			["Toxisorc"] = 2669762308,
		},
	},
```
![image](https://github.com/user-attachments/assets/1a909aac-cbb0-499a-bf77-6da88345ae7f)

**Comment by dolikemath** [comment]
Yes, I found as below:

["gold"] = {
["세나리우스"] = {
["깔끔한데"] = 95326734,
["돌진은해드릴게"] = 23367935,
["막장여병추"] = 104372342,
["나쁜성기사칠일"] = 5491587,
["굴러는드릴께"] = 41075805,
["등붉은생선"] = 72562942,
["토템은박아드릴께"] = {
["money"] = 9574156,
},
["추방자리븐"] = 135486469,
["전투폐인"] = 275840538,
},
["아즈샤라"] = {
["Tenebrislux"] = 68883234,
["창고에넣어드릴게"] = 0,
},

"세나리우스" and "아즈샤라" are realm names

**Comment by Toxicom** [comment]
Okay, I see the issue!

```lua
["토템은박아드릴께"] = {
["money"] = 9574156,
},
```

You see how `토템은박아드릴께` has a table for it's value instead of a number.

I don't know how it happened, but if you changed it to be a number, it should work.
```lua
["토템은박아드릴께"] = 9574156,
```

**Comment by dolikemath** [comment]
Oh, I has been done.

It might be from my old addons.

I changed the old ones to Toxi few days ago.

And, it is very awesome.

Anyway, I really appreciate your help.

**Comment by Toxicom** [comment]
I assume that solved your issue. Yes, it's very possible some addon (probably old) changed the database table which caused this issue.

If the issue still persists, please re-open this issue or create a new one.
