### ISSUE TITLE
[BUG] Armory: Death Knight weapon enchants

### ISSUE THREAD

**Issue by Toxicom** [Toxicom/toxiui#2]
# Description
Death Knight enchants are being abbreviated incorrectly with ✅ Short Enchant

# To Reproduce
1. Log into a Death Knight character
2. Runeforge your weapons
3. Enable ✅ Short Enchant in `/tx settings` -> Armory -> Item Slot
4. See Paper Doll frame

# Expected behavior
- [ ] Death Knight Runeforge enchants show a logical string when abbreviated
- [ ] Other enchants are also abbreviated correctly

# Screenshots
## Abbreviated
![image](https://user-images.githubusercontent.com/69549795/195210315-e13d760b-0f00-4aa2-84a0-1d2046313f9c.png)

## Full
![image](https://user-images.githubusercontent.com/69549795/195210305-a3b6171a-1e10-4167-85c6-9e3d06e59b5d.png)

# Additional Information
- Latest commit: b8d1bf1cd4150081ffc9b735bb58761c00628d14
- We could look into how WrathArmory handles it:
![image](https://user-images.githubusercontent.com/69549795/195210171-018c9b9c-56a1-465b-8dcd-b41006296c6d.png)

**Comment by Toxicom** [comment]
#4

**Comment by Toxicom** [comment]
![image](https://user-images.githubusercontent.com/69549795/198872547-80384b04-d1dc-45bf-ad26-6cb57bfee7ab.png)

**Comment by bagelbits** [comment]
I have an idea.

**Comment by Toxicom** [comment]
Think this was solved with #7 , need to test:)

**Comment by bagelbits** [comment]
I pulled up a DK I have to test right now. Will let you know in a second.

**Comment by bagelbits** [comment]
![image](https://user-images.githubusercontent.com/353626/199119711-9d6272e0-14ec-4140-bbb7-2cae132b4d69.png)
![image](https://user-images.githubusercontent.com/353626/199119743-9879eba4-3713-4bdc-b79f-8a5ab975445a.png)

Looks like it's working!
