### ISSUE TITLE
Weakaura's have leftover borders

### ISSUE THREAD

**Issue by RyadaProductions** [Toxicom/toxiui#28]
### Description

Weakaura's that use icons inside of a Progressbar, will leave a border even when the weakaura is unloaded or not displayed due to a toggle.
A small WA that we have this issue with is the following: https://wago.io/thundering-affix
It doesn't happen all the time but when switching zones it may appear (generally overworld but can also happen when going into dungeons/raids)
To get rid of them you have to either /reload or swap zone and hope for the best.

### Screenshots

![image](https://user-images.githubusercontent.com/24586388/209203523-eeef5331-7f11-4a3f-b024-6067eb1d18e9.png)

### Notes

Specifically affects `ProgressBar` WeakAura's tthat have the `Show Icon` flag checked
Multiple people that only use Weakauras, Elvui and ToxiUI have reported or seen this issue happen before.

### To reproduce

1. Add the aforementioned WeakAura to your game
2. Fly on dragon riding around the overworld (this is to make sure that the WA is unloaded
3. At zone switch the icons may or may not appear (flying out and into Valdrakken was my testcase to do it semi consistently)

### Acceptance criteria

- [ ] Empty borders shouldn't appear when WeakAura is unloaded
- [ ] Empty borders shouldn't appear when the ProgressBar is not visible

**Comment by mrbuds** [comment]
Hello, could you guys remove this insane WeakAuras module?
If you want to do skinning in WeakAuras please open a pull request to add a proper skinning support but don't replace an other addon function.

**Comment by luiepandabeertv** [comment]
Is bug inside weakaura not with toxiui. Without toxiui in got the same problem. Think need send to WA.

**Comment by Stiimo** [comment]
Hey! Does this still reproducible? I've tried to switch zone (flying out of Valdraken and returning) several times. If this was a WA bug, it could already be fixed. Please, try updating WA, ElvUI, and ToxiUI, update your profiles, and reproduce the bug.

![image](https://github.com/Toxicom/toxiui/assets/11719014/8200d496-8080-4aaa-8fbc-cb709646a220)

**Comment by RyadaProductions** [comment]
I am not sure if I can still reproduce. As I haven't played retail in a long while. I haven't seen this behavior in classic or classic-era though. I would need to install retail to test.

**Comment by Toxicom** [comment]
IIRC it used to happen only on certain WAs. Luxthos I think never caused these squares to appear

**Comment by Toxicom** [comment]
Skinning has been removed :)
https://github.com/Toxicom/toxiui/commit/bad76b1fe0950f39d402e1192baf6c4732f3b3ec
