### ISSUE TITLE
Toxi not working in Wrath anymore

### ISSUE THREAD

**Issue by tylertylerday** [Toxicom/toxiui#33]
### Description

Toxi as a whole just isn't working anymore. The colors are showing as TX:Classcolor ...etc

### Screenshots

No signs of a toxi ui with /tx

### Notes

1.

### Acceptance criteria

Generally, get Toxi working in wrath

-   [ ]

**Comment by Toxicom** [comment]
Could you please provide more information? Loaded addons, their versions atleast.

**Comment by RyadaProductions** [comment]
Isn't this generally caused by either an outdated ElvUI so Toxi doesn't load as the dependency is too low version? Make sure all your addons are updated and as Toxi said also list them here if it still doesn't work.

**Comment by Toxicom** [comment]
Also, just to confirm Wrath having no issues: 
![image](https://user-images.githubusercontent.com/69549795/213576719-5eaab6db-e76c-4a2b-8603-1faed1ca55fa.png)

**Comment by tylertylerday** [comment]
Weird, my Elvui is up to date?

![image](https://user-images.githubusercontent.com/8594827/213584674-67b98e89-27f3-4b7c-84f5-49e516d4fae7.png)

**Comment by Toxicom** [comment]
Disable every single addon except elvui & toxiui

**Comment by tylertylerday** [comment]
That didn't work :\

**Comment by tylertylerday** [comment]
Nvm got it working - it was an elvui addon either the pvp text or adibags addition.
