### ISSUE TITLE
Armory: Shield enchant

### ISSUE THREAD

**Issue by Toxicom** [Toxicom/toxiui#38]
### Description

ToxiUI's Armory is showing a missing shield enchant. Dragonflight does not have shield enchants as far as I know.

Update: off-hands should also be excluded

### Screenshots

![image](https://user-images.githubusercontent.com/69549795/216283774-39da6ebd-debd-4648-9683-594c4d739840.png)

### To reproduce

1. Equip a shield on a lvl 70 character
2. Open the Armory

### Acceptance criteria

- [ ] Armory does not show a missing shield enchant
- [ ] Armory does not show a missing off-hand enchant

**Comment by RyadaProductions** [comment]
Wrath endgame uses shield enchants yes. Major stamina, titan plating are both used in endgame as shield enchants.

**Comment by Toxicom** [comment]
> Wrath endgame uses shield enchants yes. Major stamina, titan plating are both used in endgame as shield enchants.

Just remembered Armory is disabled on wrath, so that simplifies things :D

**Comment by Toxicom** [comment]
Not only shields, but off-hands should be included too

**Comment by Toxicom** [comment]
https://github.com/Toxicom/toxiui/pull/47
