### ISSUE TITLE
Installer: Refactor installer to use the intended ElvUI's way

### ISSUE THREAD

**Issue by Toxicom** [Toxicom/toxiui#40]
### Description

Basically for compliance reasons and to keep good relationship with ElvUI, we have to re-work our installer so that it's in line with other ElvUI plugins

### Examples
- WindTools: https://github.com/fang2hou/ElvUI_WindTools
- MerathilisUI: https://github.com/Merathilis/ElvUI_MerathilisUI

### Acceptance criteria

- [ ] No custom shenanigans regarding ToxiUI installer

**Comment by Merathilis** [comment]
I will add a merge request soonish.. with the changes. I think they should be okayish 🤔

**Comment by Toxicom** [comment]
#42
