### ISSUE TITLE
Class Colors Enabled = Errors Upon Joining a New Group

### ISSUE THREAD

**Issue by hooplah64** [Toxicom/toxiui#43]
### Description

When using Class Colors (ToxiUI > Gradient Mode > Class Colors) and I join a new group, a flurry of UI errors occurs until I do /reloadui. I'm also unable to see other elements in unit frames (for example, I'm a healer, so I can no longer see the little square indicators for HoTs or support buff indicators on party frames) or even sometimes the real-time health value of the party members (health value is frozen).

SIDE NOTE: I've tried disabling Class Colors to avoid the error, but for some reason, the Evoker class color is completely broken in my UI in all instances when this feature is disabled. So in Unit Frames, Details, etc, Evokers show up as a purple color (I believe it's the same hue as a player pet would have) as opposed to their proper class color. Also want to note that the above UI error occurs in all groups, not just when Evokers are present, so unsure how/if the two issues are related.

### Screenshots

<img width="593" alt="image" src="https://user-images.githubusercontent.com/36980305/218807762-96aca2b7-d5d2-409a-8bf3-92c51a28f75b.png">

### Notes

None at this time.

### To reproduce

Enable Class Colors and join a new group.

### Acceptance criteria

Error data from bugsack:

43977x ElvUI_ToxiUI/Core/Functions/Core.lua:114: attempt to perform arithmetic on local 'a' (a nil value)
[string "@ElvUI_ToxiUI/Core/Functions/Core.lua"]:114: in function `AlmostEqual'
[string "@ElvUI_ToxiUI/Core/Functions/Color.lua"]:10: in function `EqualToRGB'
[string "@ElvUI_ToxiUI/Modules/Themes/Gradients/Update.lua"]:13: in function `SetGradientColors'
[string "@ElvUI_ToxiUI/Modules/Themes/Gradients/Power.lua"]:28: in function <...dOns/ElvUI_ToxiUI/Modules/Themes/Gradients/Power.lua:15>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@ElvUI_Libraries/Core/oUF/elements/power.lua"]:196: in function <...eElvUI_Libraries/Core/oUF/elements/power.lua:119>
[string "@ElvUI_Libraries/Core/oUF/elements/power.lua"]:208: in function <...eElvUI_Libraries/Core/oUF/elements/power.lua:200>
[string "@ElvUI_Libraries/Core/oUF/elements/power.lua"]:273: in function `func'
[string "@ElvUI_Libraries/Core/oUF/ouf.lua"]:236: in function <ElvUI_Libraries/Core/oUF/ouf.lua:219>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?

Locals:
a = nil
b = 0.247059
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'a' (a nil value)"
abs = <function> defined =[C]:-1

**Comment by Toxicom** [comment]
Is this still happening?

**Comment by hooplah64** [comment]
Yes, this issue still happens, but as much when I first submitted the bug.
Maybe 1 out of every 3 or 5 group joins. I still can't pin down a common
cause, but it does seem to happen at a higher frequency when someone from
the opposing faction joins the group.

**Comment by Stiimo** [comment]
Considering I always play with enabled Gradient Mode, I've never seen this error. Just to be sure, did you update the whole ElvUI, including the ElvUI_Libraries folder?  If so, could you, please, provide an updated error log? Because trying to backtrace the bug using your original log, I'm running into commented part of `ElvUI_Libraries/Core/oUF/ouf.lua:219`.

![image](https://github.com/Toxicom/toxiui/assets/11719014/776ba385-685c-4857-a330-9079e135af25)

**Comment by hooplah64** [comment]
I usually keep ElvUI updated, but it had been a while since I did a full
delete and reinstall. I had a whole day of no errors, but then today this
came back:

78334x ElvUI_ToxiUI/Core/Functions/Core.lua:114: attempt to perform
arithmetic on local 'a' (a nil value)
[string ***@***.***_ToxiUI/Core/Functions/Core.lua"]:114: in function
`AlmostEqual'
[string ***@***.***_ToxiUI/Core/Functions/Color.lua"]:10: in function
`EqualToRGB'
[string ***@***.***_ToxiUI/Modules/Themes/Gradients/Update.lua"]:13: in
function `SetGradientColors'
[string ***@***.***_ToxiUI/Modules/Themes/Gradients/Power.lua"]:28: in function
<...dOns/ElvUI_ToxiUI/Modules/Themes/Gradients/Power.lua:15>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string ***@***.***_Libraries/Core/oUF/elements/power.lua"]:196: in function
<...eElvUI_Libraries/Core/oUF/elements/power.lua:119>
[string ***@***.***_Libraries/Core/oUF/elements/power.lua"]:208: in function
<...eElvUI_Libraries/Core/oUF/elements/power.lua:200>
[string ***@***.***_Libraries/Core/oUF/elements/power.lua"]:273: in function
`func'
[string ***@***.***_Libraries/Core/oUF/ouf.lua"]:236: in function
<ElvUI_Libraries/Core/oUF/ouf.lua:219>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?

Locals:
a = nil
b = 0.247059
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'a' (a nil value)"
abs = <function> defined =[C]:-1

**Comment by Stiimo** [comment]
Just to be sure, can you provide a screenshot of `ElvUI_Libraries/Core/oUF/ouf.lua` around line 219?

**Comment by Toxicom** [comment]
See comment on https://github.com/Toxicom/toxiui/issues/44#issuecomment-1713306179

**Comment by Toxicom** [comment]
Closing for now
