### ISSUE TITLE
Addon Compartment Frame & ToxiUI

### ISSUE THREAD

**Issue by Stiimo** [Toxicom/toxiui#50]
### Description

With WoW 10.0 Blizzard added Addon Compartment Frame which is basically the same as WindTools Minimap Buttons Frame (see screenshots section). In 10.1 it got some improvements some addons (for example WeakAuras, ElvUI, WindTools) already use it. ElvUI already provides anchors to move it and an option to hide it. But still, many add-ons aren't integrated into it. I suggest two improvements:

1. Integrate ToxiUI into Addon Compartment
2. Move it to a convenient place or hide it during layouts installation

### Screenshots

![image](https://user-images.githubusercontent.com/11719014/236705551-fec566b3-f2cd-484d-9f2b-8ae1da7d7bf7.png)
![image](https://user-images.githubusercontent.com/11719014/236705556-120bf2d0-a348-4883-8ca9-1609ad0b745c.png)

### Notes

As for the placement, the best one is a corner of a minimap, in my opinion. But I'd like to hear other opinions. Considering, that many addons are missing from Addon Compartment, we cannot give up using WindTools Minimap Buttons. So for the time being just hiding Addon Compartment may be the best solution.

Placement example:
![image](https://user-images.githubusercontent.com/11719014/236705709-6678f324-7e9f-4617-a776-9edf2d09682c.png)

### Acceptance criteria

-   [x] ToxiUI integrated into Addon Compartment
-   [x] One of the next two:
    +   Layouts installation moves Addon Compartment to a predefined position
    +   Layouts installation hides Addon Compartment

**Comment by Stiimo** [comment]
I think I can do this, but I'd like to get some opinions on whether this should be done and a final decision about compartment placement

**Comment by luiepandabeertv** [comment]
Well, https://wowpedia.fandom.com/wiki/Addon_compartment#Automatic_registration

This is info about it

**Comment by Stiimo** [comment]
Yes, the registration part looks easy. The problem is other addons, we cannot register them ourselves

**Comment by luiepandabeertv** [comment]
> Yes, the registration part looks easy. The problem is other addons, we cannot register them ourselves

True only the other poeple of the addons can do to. We can only do ToxiUI option page.

**Comment by Toxicom** [comment]
Agree on integrating ToxiUI to addon compartment.

As for the placement/hiding, not really sure, would have to mess around with it a bit and decide what looks/feels best.

**Comment by Knuffelpanda** [comment]
ElvUI have the option to move the Addon Compartment or hide it.

**Comment by Toxicom** [comment]
Decided to not hide it, so that people get used to it & familiarized with it
https://github.com/Toxicom/toxiui/pull/51
https://github.com/Toxicom/toxiui/commit/7f2bbdca8ba07706631239a62f4aebfc3dea5ee5
https://github.com/Toxicom/toxiui/commit/4649152a22ac13afa630b014688851563c79c6bd
