### ISSUE TITLE
WoTLK Classic - Wunderbar Spec Sub-Module Right-Click Does Not Change Specialization

### ISSUE THREAD

**Issue by statuskwolek** [Toxicom/toxiui#67]
### Description
The mouseover for the spec submodule of Wunderbar indicates that left click shows talent UI, right click changes specialization.
Right now, left clicking works great -- right click does not change specialization, and in fact brings up what appears to be two action bar buttons instead (seems to work kind of like the profession popups)

### Screenshots
![image](https://github.com/Toxicom/toxiui/assets/561098/f5fce13d-e8d0-435f-ac2d-2acf26aef722)
![image](https://github.com/Toxicom/toxiui/assets/561098/6facc445-973d-4dd3-bf24-b2c9cd4c8042)
![image](https://github.com/Toxicom/toxiui/assets/561098/d045f6a4-a45c-4009-8084-43d4ee14c321)

### To reproduce
1. Buy dual specialization on any character
2. Try to switch spec using the wunderbar submodule

### Acceptance criteria
Either adjust mousover tooltip text or fix functionality :)

**Comment by Toxicom** [comment]
Trying to fix this is gonna cost me 1000 gold.. :D I'll see what I can do, I do remember dual spec not working due to the way spec switching is different from retail.. Worst case I adjust the tooltip text

**Comment by Toxicom** [comment]
Testing this right now, switching specs works, except that the icons on the flyout are borked..
https://streamable.com/2r9p8z

**Comment by statuskwolek** [comment]
Yeah just noticed this---for some reason I interpreted right click as that would kick it off and that the buttons weren't necessarily involved...

**Comment by Toxicom** [comment]
Most likely fixed in f8a8b5289cd158517792784bd53edec326f0847c -- the new behavior will be to just switch the spec without a flyout. If you don't have dual spec, tooltip won't even show right click as an available option

**Comment by Toxicom** [comment]
Please test with https://github.com/Toxicom/toxiui/releases/tag/v6.4.1-beta.4 and confirm if the issue has been resolved

**Comment by statuskwolek** [comment]
Working like a charm :)  Fixed!
