### ISSUE TITLE
Gradient Error With Game Menu Button

### ISSUE THREAD

**Issue by dsypher2** [Toxicom/toxiui#81]
Message: ...erface/AddOns/ElvUI_ToxiUI/Core/Functions/String.lua:399: attempt to index local 'left' (a nil value)
Time: Thu Oct 26 09:18:18 2023
Count: 1
Stack: ...erface/AddOns/ElvUI_ToxiUI/Core/Functions/String.lua:399: attempt to index local 'left' (a nil value)
[string "@Interface/AddOns/ElvUI_ToxiUI/Core/Functions/String.lua"]:399: in function `GradientClass'
[string "@Interface/AddOns/ElvUI_ToxiUI/Modules/Misc/GameMenuButton.lua"]:51: in main chunk

Locals: text = "October 18, 2020"
class = nil
reverse = nil
unitClass = "WARRIOR"
colorMap = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
}
left = nil
right = nil
(*temporary) = <function> defined @Interface/AddOns/ElvUI_ToxiUI/Core/Functions/String.lua:340
(*temporary) = "October 18, 2020"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'left' (a nil value)"
E = <table> {
 GetTimeInfo = <function> defined @Interface/AddOns/ElvUI/Core/General/Math.lua:354
 mylevel = 62
 Bags = <table> {
 }
 privateVars = <table> {
 }
 modules = <table> {
 }
 FormatMoney = <function> defined @Interface/AddOns/ElvUI/Core/General/Math.lua:411
 Config_OpenWindow = <function> defined @Interface/AddOns/ElvUI/Core/General/Config.lua:993
 UpdateUnitFrames = <function> defined @Interface/AddOns/ElvUI/Core/General/Core.lua:1427
 SetMoversPositions = <function> defined @Interface/AddOns/ElvUI/Core/General/Movers.lua:453
 ScheduleTimer = <function> defined @Interface/AddOns/AnnounceRare/Libraries/Ace3/AceTimer-3.0/AceTimer-3.0.lua:94
 PriestColors = <table> {
 }
 RemoveEmptySubTables = <function> defined @Interface/AddOns/ElvUI/Core/General/Core.lua:615
 Cooldown_Options = <function> defined @Interface/AddOns/ElvUI/Core/General/Cooldowns.lua:137
 Cooldown_UnbuggedTime = <function> defined @Interface/AddOns/ElvUI/Core/General/Cooldowns.lua:18
 Config_CreateFrame = <function> defined @Interface/AddOns/ElvUI/Core/General/Config.lua:790
 UIScale = <function> defined @Interface/AddOns/ElvUI/Core/General/PixelPerfect.lua:55
 db = <table> {
 }
 SetEnabledState = <function> defined @Interface/AddOns/AnnounceRare/Libraries/Ace3/AceAddon-3.0/AceAddon-3.0.lua:420
 Layout = <table> {
 }
 myRaceID = 32
 Distributor = <table> {
 }
 DBConvertSL = <function> defined @Interface/AddOns/ElvUI/Core/General/Core.lua:1246
 MountText = <table> {
 }
 INCOMPATIBLE_ADDONS = <table> {
 }
 PositionGameMenuButton = <function> defined @Interface/AddOns/ElvUI/Core/General/API.lua:600
 UIFrameFade = <function> defined @Interface/AddOns/ElvUI/Core/General/Animation.lua:361
 TimeIndicatorColors = <table> {
 }
 StaticPopup_IsLastDisplayedFrame = <function> defined @Interface/AddOns/ElvUI/Core/General/StaticPopups.lua:489
 StaticPopup_CreateSecureButton = <function> defined @Interface/AddOns/ElvUI/Core/General/StaticPopups.lua:1095
 Truncate = <function> defined @Interface/AddOns/ElvUI/Core/General/Math.lua:142
 SetupReset = <function> defined @Interface/AddOns/ElvUI/Core/General/Install.lua:537
 Config_HandleLeftButton = <function> defined @Interface/AddOns/ElvUI/Core/General/Config.lua:908
 Dump = <function> defined @Interface/AddOns/ElvUI/Core/General/API.lua:304
 WorldMap = <table> {
 }
 Disable = <function> defined @Interface/AddOns/AnnounceRare/Libraries/Ace3/AceAddon-3.0/AceAddon-3.0.lua:310
 TimeColors = <table> {
 }
 SlideOut = <function> defined @Interface/AddOns/ElvUI/Core/General/Animation.lua:296
 Unhook = <function> defined @Interface/AddOns/AnnounceRare/Libraries/Ace3/AceHook-3.0/AceHook-3.0.lua:417
 XPIsTrialMax = <function> defined @Interface/AddOns/ElvUI/Core/General/API.lua:553
 StaticPopup_GetAllSecureButtons = <function> defined @Interface/AddOns/ElvUI/Core/General/StaticPopups.lua:1119
 EscapeString = <function> defined @Interface/AddOns/ElvUI/Core/init.lua:213
 RGBToHex = <function> defined @Interface/AddOns/ElvUI/Core/General/Math.lua:147
 ClickGameMenu = <function> defined @Interface/AddOns/ElvUI/Core/General/A

**Comment by Toxicom** [comment]
Could you please follow the issue template and provide more information?

**Comment by Toxicom** [comment]
Closing issue since it's stale
