### ISSUE TITLE
6.4.7-Beta7 -- Issue with Custom Text (Name) Position for Party in Healer Layout

### ISSUE THREAD

**Issue by statuskwolek** [Toxicom/toxiui#82]
### Description
When using the healer layout, and joining a party, the custom text for name overlaps with the health percentage.  I'm fairly certain this isn't supposed to happen.

### Screenshots
![image](https://github.com/Toxicom/toxiui/assets/561098/95e95799-765b-4f91-bcc8-ab6e49788dd6)
![image](https://github.com/Toxicom/toxiui/assets/561098/bf24f497-0294-4c5a-855b-f041831b4704)
![image](https://github.com/Toxicom/toxiui/assets/561098/4e02d780-9bcb-435c-9829-f6378d682d68)

### Notes
WoTLK Classic

### To reproduce
1. Set role as healer during install
2. Run through installer
3. Join a group

### Acceptance criteria
The last image is a suggestion for positioning -- this is of course at someone else's discretion and could be individually adjusted in each install.  Somehow the overlap does not look intentional...

- [ ]

**Comment by Toxicom** [comment]
The screenshots you posted do not look like default ToxiUI profile
![image](https://github.com/Toxicom/toxiui/assets/69549795/e8288fb0-68f5-4b1b-b29b-3176ac31e917)

**Comment by statuskwolek** [comment]
Literally just ran the install on a disc priest w/ the healer layout -- my frames look more like yours but still w/ the overlap -- guessing the font settings in the previous profiles don't get overridden and the overlap is caused by a blockier font than the one you're using.  I'll go ahead and continue to move it to a better spot where there's no hope of overlapping

**Comment by Toxicom** [comment]
Check in ToxiUI font settings if you haven't replaced the Title font

**Comment by statuskwolek** [comment]
Yeah -- my settings there are retained and not using the default font -- local issue then and guessing most people don't change from your default so don't run into it...I'm just going to move it down anyway :)
