### ISSUE TITLE
AFK mode keeps turning itself on.

### ISSUE THREAD

**Issue by ErisKyn** [Toxicom/toxiui#87]
### Description
ToxiUI is turning AFK mode on by itself. 
This issue is occurring on Wow Classic SOD with latest Elvui 13.54. 
I tried both ToxiUI 6.5.1 and ToxiUI beta 6.5.2 beta 3.
WOW is running as administrator. 

### Screenshots
Here is a video.
https://www.youtube.com/watch?v=bnYcQ23vtWM

### To reproduce
Turn off all addons but ElvUI + ToxiUI, afk mode does not stay off if UI is reloaded.
If ToxiUI is disabled, then ElvUI will keep AFK mode off after UI is reloaded.

**Comment by Toxicom** [comment]
@ErisKyn 
Disable the ToxiUI AFK module first before turning off the ElvUI one. It's in ToxiUI settings -> Skins (I think)

edit: thanks for video, helped understand the issue!
