### ISSUE TITLE
ToxiUI Errors after update to latest

### ISSUE THREAD

**Issue by Stalmard** [Toxicom/toxiui#89]
Started receiving LUA errors after updating to latest version.  The error persisted even after renaming WTF folder.  LUA error below:

```lua
10x ...I_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua:43: attempt to index local 'configInfo' (a nil value)
[string "@ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua"]:43: in function `GetLoadoutName'
[string "@ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua"]:378: in function `UpdateElement'
[string "@ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua"]:408: in function `UpdateElements'
[string "@ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua"]:182: in function <...I_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua:179>

Locals:
self = <table> {
 OnEnter = <function> defined @ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua:65
 spec2Text = FontString {
 }
 EnableModule = <function> defined @Decursive/Libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 baseName = "ElvUI_ToxiUI"
 IterateEmbeds = <function> defined @Decursive/Libs/AceAddon-3.0/AceAddon-3.0.lua:438
 LogTrace = <function> defined @ElvUI_ToxiUI/Core/Functions/Log.lua:148
 GetWrathCacheForSpec = <function> defined @ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua:189
 infoSpec = 3
 UpdatePosition = <function> defined @ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua:271
 defaultModuleState = true
 IsEnabled = <function> defined @Decursive/Libs/AceAddon-3.0/AceAddon-3.0.lua:447
 DisableModule = <function> defined @Decursive/Libs/AceAddon-3.0/AceAddon-3.0.lua:346
 ThrowError = <function> defined @ElvUI_ToxiUI/Core/Functions/Log.lua:83
 LogInfo = <function> defined @ElvUI_ToxiUI/Core/Functions/Log.lua:138
 UpdateSwitch = <function> defined @ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua:413
 forceHideSpec2 = false
 OnWunderBarUpdate = <function> defined @ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua:177
 enabledState = true
 infoText = FontString {
 }
 GetLoadoutName = <function> defined @ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua:35
 IterateModules = <function> defined @Decursive/Libs/AceAddon-3.0/AceAddon-3.0.lua:433
 UpdateElements = <function> defined @ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua:407
 isEnabled = false
 frame = Frame {
 }
 Module = TXUIWunderBarMiddlePanelModule1 {
 }
 UpdateSpecialization = <function> defined @ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua:227
 Enable = <function> defined @Decursive/Libs/AceAddon-3.0/AceAddon-3.0.lua:290
 numSpecs = 3
 Data = <table> {
 }
 GetModule = <function> defined @Decursive/Libs/AceAddon-3.0/AceAddon-3.0.lua:206
 specCache = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 CreateSwitch = <function> defined @ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua:421
 Initialized = true
 GetName = <function> defined @Decursive/Libs/AceAddon-3.0/AceAddon-3.0.lua:275
 name = "ElvUI_ElvUI_ToxiUI_WunderBar_SpecSwitch"
 SubModuleHolder = Frame {
 }
 UpdateInfoText = <function> defined @ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua:347
 Disable = <function> defined @Decursive/Libs/AceAddon-3.0/AceAddon-3.0.lua:310
 spec1Text = FontString {
 }
 OnInit = <function> defined @ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua:478
 SetDefaultModuleLibraries = <function> defined @Decursive/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 spec1 = 3
 IsModule = <function> defined @Decursive/Libs/AceAddon-3.0/AceAddon-3.0.lua:213
 NewModule = <function> defined @Decursive/Libs/AceAddon-3.0/AceAddon-3.0.lua:231
 SetDefaultModuleState = <function> defined @Decursive/Libs/AceAddon-3.0/AceAddon-3.0.lua:383
 OnClick = <function> defined @ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua:55
 OnLeave = <function> defined @ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua:75
 SetDefaultModulePrototype = <function> defined @Decursive/Libs/AceAddon-3.0/AceAddon-3.0.lua:405
 SpecEnter = <function> defined @ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua:85
 spec2Frame = Button {
 }
 LogWarning = <function> defined @ElvUI_ToxiUI/Core/Functions/Log.lua:133
 LogDebug = <function> defined @ElvUI_ToxiUI/Core/Functions/Log.lua:143
 spec1Icon = FontString {
 }
 SpecLeave = <function
```

**Comment by Toxicom** [comment]
Would be great to have more information, like `/tx status`, how to reproduce, etc.

**Comment by Stalmard** [comment]
![image](https://github.com/Toxicom/toxiui/assets/160372106/79ed082c-1bfa-4712-afee-6bca969370a9)

I am not sure if that actually uploaded the /tx status screen snippet or not.  Please let me know.

**Comment by Toxicom** [comment]
@Stalmard I see you closed the issue, was the error resolved?

**Comment by Stalmard** [comment]
Sorry, I must have moved my mouse while sending the incident.  The problem still exists.

**Comment by Toxicom** [comment]
@Stalmard Have you noticed a pattern of when the error occurs? I haven't been able to reproduce it even once 😞

**Comment by Stalmard** [comment]
It happens on every log in to each toon.  It will also happen each time you zone into a dungeon or instance.  Those are the consistant ones I have.  More than welcome to hop into discord and share my screen with you.

**Comment by Toxicom** [comment]
Before we do that, could you show me what's the situation with your talent loadouts?
![image](https://github.com/Toxicom/toxiui/assets/69549795/ac48a286-72a4-40e3-9750-75d067ee35ce)

I also assume if you turn off `Show Loadout Names`, the error goes away?
![image](https://github.com/Toxicom/toxiui/assets/69549795/ef777261-db8f-4243-acf3-33bced69bce8)

**Comment by Stalmard** [comment]
![image](https://github.com/Toxicom/toxiui/assets/160372106/d32e6a28-8771-4431-a1a4-e64768b0f13a)


Error still happened after turning off "show load out names" with this info:

5x ...I_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua:43: attempt to index local 'configInfo' (a nil value)
[string "@ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua"]:43: in function `GetLoadoutName'
[string "@ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua"]:378: in function `UpdateElement'
[string "@ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua"]:408: in function `UpdateElements'
[string "@ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua"]:182: in function <...I_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua:179>

Locals:
self = <table> {
 OnEnter = <function> defined @ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua:65
 spec2Text = FontString {
 }
 EnableModule = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 baseName = "ElvUI_ToxiUI"
 IterateEmbeds = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:438
 LogTrace = <function> defined @ElvUI_ToxiUI/Core/Functions/Log.lua:148
 GetWrathCacheForSpec = <function> defined @ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua:189
 UpdatePosition = <function> defined @ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua:271
 defaultModuleState = true
 IsEnabled = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:447
 DisableModule = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:346
 ThrowError = <function> defined @ElvUI_ToxiUI/Core/Functions/Log.lua:83
 LogInfo = <function> defined @ElvUI_ToxiUI/Core/Functions/Log.lua:138
 UpdateSwitch = <function> defined @ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua:413
 forceHideSpec2 = false
 OnWunderBarUpdate = <function> defined @ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua:177
 enabledState = true
 infoText = FontString {
 }
 GetLoadoutName = <function> defined @ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua:35
 IterateModules = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:433
 UpdateElements = <function> defined @ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua:407
 isEnabled = false
 frame = Frame {
 }
 Module = TXUIWunderBarMiddlePanelModule1 {
 }
 UpdateSpecialization = <function> defined @ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua:227
 Enable = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:290
 numSpecs = 3
 Data = <table> {
 }
 GetModule = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:206
 specCache = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 CreateSwitch = <function> defined @ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua:421
 Initialized = true
 GetName = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:275
 name = "ElvUI_ElvUI_ToxiUI_WunderBar_SpecSwitch"
 SubModuleHolder = Frame {
 }
 UpdateInfoText = <function> defined @ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua:347
 Disable = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:310
 spec1Text = FontString {
 }
 OnInit = <function> defined @ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua:478
 SetDefaultModuleLibraries = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 spec1 = 3
 IsModule = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:213
 NewModule = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:231
 SetDefaultModuleState = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:383
 OnClick = <function> defined @ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua:55
 OnLeave = <function> defined @ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua:75
 SetDefaultModulePrototype = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:405
 SpecEnter = <function> defined @ElvUI_ToxiUI/Modules/WunderBar/SubModules/SpecSwitch.lua:85
 spec2Frame = Button {
 }
 LogWarning = <function> defined @ElvUI_ToxiUI/Core/Functions/Log.lua:133
 LogDebug = <function> defined @ElvUI_ToxiUI/Core/Fun

**Comment by Toxicom** [comment]
Okay, it looks like you don't have a loadout selected and therefore it's erroring, which is weird, cause I did test this with a new character who also didn't have a loadout selected..

Regardless, I've added some extra code to check if the `configInfo` object is available before accessing it and releasing a `v6.5.6-beta.1` as we speak -- do you mind testing with that beta build and see if that resolved your issue?

[Build v6.5.6-beta.1](https://github.com/Toxicom/toxiui/releases/tag/v6.5.6-beta.1)

**Comment by Stalmard** [comment]
Will do.

**Comment by Stalmard** [comment]
No more fatalities!  You are AWESOME!

**Comment by Toxicom** [comment]
Awesome, thanks for the report!
