### ISSUE TITLE
Hearthstone toy Effects on Hearthstone button click.

### ISSUE THREAD

**Issue by Fendoran** [Toxicom/toxiui#90]
There is no Issue, clicked on the link on discord that said "Bugs & Suggestions".

I love your addon mate, nothing to be said about it, however, I do have a cool feature I'd like to suggest.

You know how you have this button at the bottom of the screen that you can click to hearthstone. 
- we all keep getting toys for cool hearthstone animation, barely anyone uses them due to the fact that it's a toy and it takes up space, how about you integrate these toys into your addon, so that when you click this hearthstone teleport button a randomized effect where it choses one random hearthstone toy effect each time, or a setting to choose what effect it will be each time. would be a cool little feature ^^

**Comment by Toxicom** [comment]
Hi, thanks for the suggestion! Ill think about a randomizer feature, as you can already select which hearthstone to use in wunderbar settings :)

**Comment by Fendoran** [comment]
Oh shoot!, yes you can xD silly me, you already thought about it, amazing, yeah a randomizer feature would be awesome :)

**Comment by Toxicom** [comment]
Random hearthstone added with a469fa28dfedee19817f473796f875dfe10d0b8c, open new issue if bugs are found
