### ISSUE TITLE
When I enter arena I get error constantly

### ISSUE THREAD

**Issue by Yakrel** [Toxicom/toxiui#91]
### Description
Its happening on arena

### Lua error
```lua
Message: ...terface/AddOns/ElvUI_ToxiUI/Core/Functions/Color.lua:14: bad argument #2 to 'SetGradient' (Usage: self:SetGradient(orientation, minColor, maxColor))
Time: Mon Apr 22 18:33:20 2024
Count: 8258
Stack: ...terface/AddOns/ElvUI_ToxiUI/Core/Functions/Color.lua:14: bad argument #2 to 'SetGradient' (Usage: self:SetGradient(orientation, minColor, maxColor))
[string "=[C]"]: ?
[string "=[C]"]: in function `SetGradient'
[string "@Interface/AddOns/ElvUI_ToxiUI/Core/Functions/Color.lua"]:14: in function `SetGradient'
[string "@Interface/AddOns/ElvUI_ToxiUI/Modules/Themes/Gradients/Update.lua"]:82: in function `SetGradientColors'
[string "@Interface/AddOns/ElvUI_ToxiUI/Modules/Themes/Gradients/Health.lua"]:58: in function <...Ons/ElvUI_ToxiUI/Modules/Themes/Gradients/Health.lua:42>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/oUF/elements/health.lua"]:140: in function <.../AddOns/ElvUI_Libraries/Core/oUF/elements/health.lua:86>
[string "@Interface/AddOns/ElvUI_Libraries/Core/oUF/elements/health.lua"]:152: in function <.../AddOns/ElvUI_Libraries/Core/oUF/elements/health.lua:144>
[string "@Interface/AddOns/ElvUI_Libraries/Core/oUF/elements/health.lua"]:206: in function `func'
[string "@Interface/AddOns/ElvUI_Libraries/Core/oUF/ouf.lua"]:1073: in function `run'
[string "@Interface/AddOns/ElvUI_Libraries/Core/oUF/ouf.lua"]:1110: in function `execute'
[string "@Interface/AddOns/ElvUI_Libraries/Core/oUF/ouf.lua"]:1123: in function `update'
[string "@Interface/AddOns/ElvUI_Libraries/Core/oUF/ouf.lua"]:1154: in function <Interface/AddOns/ElvUI_Libraries/Core/oUF/ouf.lua:1152>

Locals: (*temporary) = <function> defined =[C]:-1
```

### ToxiUI Status Report
![image](https://github.com/Toxicom/toxiui/assets/85676216/3199766d-a1d0-4f20-9abd-1e069dbd25f4)

### Screenshots
![image](https://github.com/Toxicom/toxiui/assets/85676216/c9a51649-3a8d-45da-b342-a702ba965cd9)
![image](https://github.com/Toxicom/toxiui/assets/85676216/e893533b-97ad-480f-94d6-d28d96ebaa9e)

### To reproduce
If this issue is describing a bug, include some steps to reproduce the behavior

1.
2.
3.

**Comment by Toxicom** [comment]
Thanks for the report. PvP historically always has had some bugs because in PvP the data is sometimes delayed and we error out cause there's no data. I keep adding patches and fallbacks but there's a lot of those. I'll do something about this error, too.

**Comment by Toxicom** [comment]
@Yakrel I added some safety checks and fallbacks, can you please test with the latest [`v6.5.9-beta.3`](https://github.com/Toxicom/toxiui/releases/tag/v6.5.9-beta.3) and see if you can reproduce the issue again?

**Comment by Yakrel** [comment]
> @Yakrel I added some safety checks and fallbacks, can you please test with the latest [`v6.5.9-beta.3`](https://github.com/Toxicom/toxiui/releases/tag/v6.5.9-beta.3) and see if you can reproduce the issue again?

I will try it.

**Comment by Yakrel** [comment]
Looks like no error for now ty.
