### ISSUE TITLE
Class Icon/Symbol apperaing as a block on splash screen

### ISSUE THREAD

**Issue by J0my** [Toxicom/toxiui#95]
### Description
When I press escape and it shows the ToxiUI splash screen, where the char name and icon/symbol and class is shown, the icon/symbol is a square like a font error. Also in the fonts changer the font for ToxiUIIcons shows up again as the font squares. In the attached screenshots you can see where the icon/symbol is displaying correctly in the armory and on the Wunderbar.

### ToxiUI Status Report
![Screenshot 2024-06-12 094334](https://github.com/Toxicom/toxiui/assets/32807897/8e3d3d31-2eb8-45d9-8133-e4e9a932b8d0)

### Screenshots
![Screenshot 2024-06-12 093909](https://github.com/Toxicom/toxiui/assets/32807897/cc217672-4744-4781-b235-b3b46119b755)
![Screenshot 2024-06-12 093950](https://github.com/Toxicom/toxiui/assets/32807897/a64fcae7-acc2-411b-8603-4b0778993644)

**Comment by Toxicom** [comment]
The `ToxiUIIcons` font is irrelevant here, because in the Game Menu we're using the primary `- ToxiUI` font. If you have it changed then it makes sense that it's showing a square.

Can you try re-installing the addon completely fresh and let me know if the issue persists? Your profile settings will not disappear if you delete the addon.

**Comment by J0my** [comment]
Hello thanks for the reply, I have not changed the fonts they are all the defaults. I have tried reinstalling the addon and the issue has still persisted

**Comment by Toxicom** [comment]
@J0my Can you go to your WoW installation, then `_retail_/Interface/AddOns/ElvUI_ToxiUI/Media/Fonts/` and attach the `ToxiUI.ttf` here?

To make sure you're going to the right place, follow these instructions: https://github.com/tukui-org/ElvUI/wiki/install#open-your-battlenet-app-and-select-world-of-warcraft---then-click-on-the-options-dropdown-cogwheel-icon

**Comment by J0my** [comment]
[ToxiUI.zip](https://github.com/user-attachments/files/15803114/ToxiUI.zip)

Here is the font you requested, I had to put it in a .zip as it would not upload the font file format

**Comment by Toxicom** [comment]
I've opened the font you sent and I do see the spec icons.
![image](https://github.com/Toxicom/toxiui/assets/69549795/2605d262-1510-48e2-9f39-ecdf0134e3e8)

The `59649` unicode also matches what's defined in code: https://github.com/Toxicom/toxiui/blob/development/Core/Profile.lua#L943

I'm very confused on why it's not working 😕 

One more option I can think of is separating the spec icon from the rest of the level text and specifying the icons font for it, but that will mean I can't have it inline with the rest of the text 🤔

**Comment by Toxicom** [comment]
@J0my Do you mind doing some additional troubleshooting? I am releasing a `v6.6.8-beta.1` build with additional code and debugging added.

Can you please install these 3 AddOns:
- [BugGrabber](https://www.curseforge.com/wow/addons/bug-grabber)
- [BugSack](https://www.curseforge.com/wow/addons/bugsack)
- [DevTool](https://www.curseforge.com/wow/addons/devtool)

And then also update to https://github.com/Toxicom/toxiui/releases/tag/v6.6.8-beta.1

Once you have all that in place, make sure to first `/reload` in game, then follow these steps:
1. Open the Game Menu
2. See if the issue still persists
3. Close the Game Menu
4. Type `/dev` in chat
5. A new window should show up with various data logged there
6. Send a screenshot of that `/dev` window here

Throughout all of these steps see if you're getting any errors (fatality sound) in your BugSack. This will hopefully provide me more information and help narrow down the cause.

**Comment by J0my** [comment]
Hello, thanks again for the replies, I have installed the 3 mods as well as the toxi beta. I followed the instructions and the issue still persists. Below is the image you requested of the /dev command. There seems to be no bugs that have occurred during all of this. I am happy to keep trying anything you need to try help solve the issue. 

![image](https://github.com/Toxicom/toxiui/assets/32807897/fc68015d-18cc-450b-b6fb-7f00b1a66200)

**Comment by Toxicom** [comment]
I assume if you click on this `iconsDb`:
![image](https://github.com/Toxicom/toxiui/assets/69549795/bd819242-1d55-4864-91f8-1be37eb3e144)

All of the entries there are also empty squares? If so, it's definitely a font issue, which.. doesn't make sense 😆

**Comment by J0my** [comment]
![image](https://github.com/Toxicom/toxiui/assets/32807897/1ef8d3cd-4a68-433a-89e6-11f5f025ae1b)
Yes they are all squares. It could just be my system it is happening on, I just dont have another pc to test it on to see lol.

**Comment by J0my** [comment]
I had installed the font itself on my computer and opened it up on character map and it shows them all there. 

![image](https://github.com/Toxicom/toxiui/assets/32807897/9e9cd34a-42f4-41c7-a2fb-2db01b0a1038)

**Comment by Toxicom** [comment]
> I had installed the font itself on my computer and opened it up on character map and it shows them all there.
> 
> ![image](https://private-user-images.githubusercontent.com/32807897/338957798-9e9cd34a-42f4-41c7-a2fb-2db01b0a1038.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxOTQwMDUsIm5iZiI6MTcxODE5MzcwNSwicGF0aCI6Ii8zMjgwNzg5Ny8zMzg5NTc3OTgtOWU5Y2QzNGEtNDJmNC00MWM3LWEyZmItMmRiMDFiMGExMDM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDEyMDE0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkNDg0MDc3NjQwN2M4MjU4M2QyMmU5OTVlNzQ1YjU5ZjMxZTkyNjA0MzdhZGZlYzk0OWMxZjk3NTFjYTkwMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oMc_T-_26N6RyhqtNPw6CI6VEptddO7fgjvHVrChJHo)

But this is `ToxiUIIcons` font which we're not using for that specific place. Can you take a look at the `ToxiUI` font and see if those glyphs are there?

**Comment by J0my** [comment]
![image](https://github.com/Toxicom/toxiui/assets/32807897/1ee6d385-f578-49f9-b548-7d0c0ce499e5)
They do appear to still be there on the main ToxiUI font

**Comment by Toxicom** [comment]
Alright.. let's try to do some code editing..
Can you open https://github.com/Toxicom/toxiui/blob/development/Core/Profile.lua this file on your local machine, then change
```lua
[251] = F.String.ConvertGlyph(59649), -- Death Knight Frost
```
to
```lua
[251] = "", -- dk frost
```
This way instead of converting the unicode to a glyph, we are using the glyph directly. Perhaps there's an issue with the way we handle unicode 🤔 

After that, restart your game just to be safe and see if the issue is still there.

**Comment by J0my** [comment]
![image](https://github.com/Toxicom/toxiui/assets/32807897/37351850-a40d-4c73-a3b1-9dc8f8db1c95)
![image](https://github.com/Toxicom/toxiui/assets/32807897/8f7394df-cf10-4eda-9df1-fc6a358e3a5e)
It is still there unfortunately, I edited the file you mentioned

**Comment by Toxicom** [comment]
I noticed your name has the incorrect font, too. For reference, this is what it should look like:
![image](https://github.com/Toxicom/toxiui/assets/69549795/b1a1fea7-5088-4556-a7d4-5c120b841b64)

Are you sure you didn't change any font files in the AddOn? Because that is the only logical explanation as for why the spec icon does not get recognized.

**Comment by J0my** [comment]
I created a fresh char and did a stock install of elvui+toxi and it works, I am pretty sure I know what was the cause of setting a diff font for the ui on other toons and importing those profiles onto it. Apologies for the inconvenience, you can close this issue. I am loving interface though!

![image](https://github.com/Toxicom/toxiui/assets/32807897/28886122-e07e-41af-b8c2-918ed4458691)

**Comment by Toxicom** [comment]
It's still weird though, since that font is being set in the code without any option to change it, so it's very odd.. Regardless, good to know it's been solved.
