### ISSUE TITLE
Collection button in wunderbar do not display

### ISSUE THREAD

**Issue by Genginzu** [Toxicom/toxiui#96]
### Description
Collection button in the wunderbar do not display even if the option is activated.

### Lua error
```lua
No error display
```

### ToxiUI Status Report
Type `/tx status` in game and paste a screenshot of it here.
![image](https://github.com/Toxicom/toxiui/assets/8217063/b52b5304-5730-4c49-a20e-1a58dea984d6)

### Screenshots
Wunderbar: 
![image](https://github.com/Toxicom/toxiui/assets/8217063/2883d704-7580-4e74-9a27-bb49b83d0497)

Option Collections for the wunderbar selected
![image](https://github.com/Toxicom/toxiui/assets/8217063/2292e414-b9d9-4236-b7d9-be43e9e05dd7)

### To reproduce
No steps to reproduce.

**Comment by Toxicom** [comment]
Please include reproduction steps, as it works for me no issues.

**Comment by Genginzu** [comment]
I do not touch anything.
I just launch the elvui installer, then the Toxiui installer.
Collection button is not display even if activated.

As you see in my screenshot the option is activated.

What else do you need ? :)

Thank you !

**Comment by Toxicom** [comment]
Can you check if you have this enabled?

![image](https://github.com/Toxicom/toxiui/assets/69549795/e447d048-c3af-4c66-b8d4-d2ff967c4482)

**Comment by Toxicom** [comment]
Oh, nevermind, I misunderstood the issue..

It's not displayed because you have too many icons enabled and therefore they do not fit in the bar. Disable some icons in MicroMenu and you will see Collections appear :)
