### ISSUE TITLE
Is it possible to get a bigger character frame ?

### ISSUE THREAD

**Issue by Genginzu** [Toxicom/toxiui#97]
### Description
From my point of view the size of character frame is a little bit small.
Could it be possible to get a bigger frame ?

### Lua error
```lua
No error
```

### ToxiUI Status Report
![image](https://github.com/Toxicom/toxiui/assets/8217063/0604ada6-d8d9-468e-b40c-39d8631587ca)

### Screenshots
![image](https://github.com/Toxicom/toxiui/assets/8217063/01c88f71-dcd4-4932-a307-16fc6fe8c0bf)

### To reproduce
No step because it's a question :)
Thank you !

**Comment by Toxicom** [comment]
![image](https://github.com/Toxicom/toxiui/assets/69549795/321c77b9-5fc4-46ea-b29e-c79443cc33bd)
